- media_driver/linux/common/ddi/media_libva.cpp
num_attribs parameter is an "out" parameter.  Therefore, there is no
contract with caller about its input value.
Fixes #15
Signed-off-by: U. Artie Eoff <ullysses.a.eoff@intel.com>
> DdiMedia_QueryConfigAttributes: do not check input value of num_attribs

- media_driver/linux/common/ddi/media_libva.cpp
When making default VA surfaces ffmpeg always sets this attribute to avoid surprises - this change fixes surface creation in ffmpeg and allows decoding to work.
> Allow VA memory type

- media_driver/linux/common/ddi/media_libva.cpp
iHD decoder dump NV12 U/V date is wrong, root casue is when calc data
size, need tp celing the width with 32 or 64.
> media_libva: fix iHD decoder dump NV12 format UV error issue.

- media_driver/linux/common/ddi/media_libva_caps.cpp
Per va.h documentation, vaQuerySurfaceAttributes must
adjust numAttribs when VA_STATUS_ERROR_MAX_NUM_EXCEEDED.
Fixes #12
Signed-off-by: U. Artie Eoff <ullysses.a.eoff@intel.com>
> libva_caps: adjust numAttribs when max num is exceeded

- media_driver/agnostic/common/cm/cm_queue_rt.cpp
fix the build warning: this ‘if’ clause does not guard.
> Fix the build warning about ‘if’ clause does not guard.

- media_driver/linux/common/ddi/media_libva.h
This adds "Intel iHD driver" so that the driver can be identified from the vendor string.
The i965 driver also includes the platform and more version information (e.g. "Intel i965 driver for Intel(R) Kaby Lake - 2.0.1.pre1 (2.0.0-20-g76d9e59)"), but that is somewhat more involved to obtain and really the driver name is the most important thing.
> Make the vendor string more descriptive

- media_driver/linux/common/codec/ddi/media_ddi_encode_hevc.cpp
description:driver should use mb_rate_control to control the MBBRC
user just need to set the typical BRC control methold
it's a fix for #8 
Signed-off-by: xinfengz <carl.zhang@intel.com>
> fix for HEVC MBBRC issue

- media_driver/linux/common/ddi/media_libva_caps.cpp
- media_driver/linux/common/ddi/media_libva_caps.h
add vaQuerySurfaceAttributes support for encode
fix issue #9 
> add vaQuerySurfaceAttributes support for encode

- media_driver/linux/common/codec/ddi/media_ddi_decode_vp8.cpp
Only no-key frame have last/gold/alt reference frame, add more
check for this case.
Fix #48 
> vp8dec: fix the last/gold/alt referenc frame check in key frame.

- media_driver/linux/common/codec/ddi/media_ddi_encode_avc.cpp
- media_driver/linux/common/codec/ddi/media_ddi_encode_fei_avc.cpp
- media_driver/linux/common/codec/ddi/media_ddi_encode_fei_hevc.cpp
- media_driver/linux/common/codec/ddi/media_ddi_encode_hevc.cpp
- media_driver/linux/common/codec/ddi/media_ddi_encode_mpeg2.cpp
- media_driver/linux/common/codec/ddi/media_ddi_encode_vp9.cpp
- media_driver/linux/common/codec/ddi/media_libva_decoder.cpp
- media_driver/linux/common/codec/ddi/media_libva_decoder.h
- media_driver/linux/common/ddi/media_libva.cpp
- media_driver/linux/common/ddi/media_libva_util.cpp
- media_driver/linux/common/ddi/media_libva_util.h
with this fix, application can set the context tied surface with vaCreateSurface
also it can register the recon & ref into context tied surface by vaRenderPicture
fix issue #25 
> dynamic register recon/ref surfaces for encode

- cmrtlib/linux/CMakeLists.txt
This fix also removes cmrt dependency from libva-x11 which it actually
does not have.
Fixes #63
Change-Id: I85ea2f5b2f330bc1bae77f15e2a32b9a8e4adf9d
> Fix cmrt build if libva installed at custom location

- media_driver/linux/common/codec/ddi/media_ddi_encode_avc.cpp
- media_driver/linux/common/codec/ddi/media_ddi_encode_hevc.cpp
- media_driver/linux/common/codec/ddi/media_ddi_encode_mpeg2.cpp
- media_driver/linux/common/codec/ddi/media_libva_encoder.cpp
- media_driver/linux/common/codec/ddi/media_libva_encoder.h
> keep quality level until new VAEncMiscParameterBufferQualityLevel

- media_driver/linux/common/ddi/media_libva.h
set the max_display_attributes to be zero, middle ware should check the vaMaxNumDisplayAttributes, if it is zero, should not call the vaGet/QueryDisplayAttributes.
> change the max_display_attributes to be zero

- media_driver/linux/common/os/libdrm/xf86drm.c
In newer GNU C Library, makedev is deprecated in sys/types.h
and will be removed soon.  makedev was moved to sys/sysmacros.h
header instead.
Fixes #94
Signed-off-by: U. Artie Eoff <ullysses.a.eoff@intel.com>
> xf86drm.c: include sys/sysmacros.h for makedev support

- media_driver/agnostic/common/shared/media_perf_profiler.cpp
Fix timestamp address align issue for perf profiler for Linux
Author: Li, Xiaogang <xiaogang.li@intel.com>
> Fix timestamp address align issue for perf profiler for Linux

- media_driver/linux/common/codec/ddi/media_ddi_decode_vc1.cpp
in VA-API 2.0, b_picture_fraction means the index for
PICTURE_LAYER::BFRACTION value in Table 40 (7.1.1.14).
fix issue #21.
> vc1dec: fix the b_picture_fraction semantic issue.

- media_driver/linux/ult/libdrm_mock/xf86drm_mock.c
commit f0b683b fix the libdrm part, but missing the drm mock test.
> xf86drm_mock: include sys/sysmacros.h for makedev support.

- media_driver/media_top_cmake.cmake
Different compiler versions often generate different
warnings that aren't always addressed (or tested)
immediately.  See #88 for example.
Allow fatal warnings (-Werror) to be turned off if
desired/necessary.  -DMEDIA_BUILD_FATAL_WARNINGS=[ON|OFF]
can be specified during cmake configure to enable/disable
fatal warnings.
Signed-off-by: U. Artie Eoff <ullysses.a.eoff@intel.com>
> cmake: allow fatal warnings to be disabled during build

- media_driver/linux/common/ddi/media_libva_putsurface_linux.cpp
- media_driver/linux/common/ddi/media_libva_putsurface_linux.h
vaapi update caused incompatible issue
including function name etc.
> fix X11 put surface issue

- media_driver/linux/gen9/ddi/media_libva_caps_g9.cpp
Setting Priority Level and QP Delta ROI support flags.
> [HEVC Encode] - Setting ROI support flags for Gen9

- media_driver/linux/common/os/mos_utilities_specific.c
The event tracing code uses a const char array and bit shifts to convert byte
values (to be output into the trace) into two-character hex representation
through addressing the const array depending on the byte value. Since
char is signed, using char to represent byte values sometimes leads to
addressing an element of the const char array by a negative index. Replaced
with unsigned char.
> [MOS] Fix signed bit shifts leading to out-of-bounds access

- media_driver/linux/common/ddi/media_libva_caps.cpp
fix the incorrect return for 10 bit HEVC encode on CNL+ platform
> check the support RT format inside CreateConfig

- media_driver/linux/common/ddi/media_libva_putsurface_linux.h
libva-x11.so is a linker name and is not available in the runtime
environment (if libva-devel package is not installed). Thus, on-screen
rendering with X Server will not work. This patch changes to use
soname instead.
Fixes: #150
Change-Id: I82b9943c10a9d8f0e7d12c824ebcddd9c6b6b0bd
> Use libva-x11.so.2 soname for dlopen

- media_driver/linux/common/codec/ddi/media_ddi_encode_hevc.cpp
- media_driver/linux/common/ddi/media_libva.cpp
when return with error status, need to unlock the mutex.
> ddi/media_libva: fix mutex lock issue

- media_driver/agnostic/common/codec/hal/codechal_decode_jpeg.h
- media_driver/agnostic/common/codec/hal/codechal_setting.h
- media_driver/linux/common/codec/ddi/media_ddi_decode_jpeg.cpp
we need one VAAPI flag to disable/control SFC in decode. now we using VA_DEC_PROCESSING flag.
maybe we need a new one in the next.
Signed-off-by: Zhang, Owen <owen.zhang@intel.com>
> add SFC flag for decode.

- media_driver/agnostic/common/codec/hal/codechal_encode_mpeg2.cpp
encode work by f_code and macroblock_address changes.
Signed-off-by: Jing SUN <jing.a.sun@intel.com>
> [ffmpeg-vaapi][mpeg2 encode] make ffmpeg's mpeg2 vaapi

- media_driver/cmake/linux/media_compile_flags_linux.cmake
- media_driver/linux/common/os/mos_context_specific.cpp
After applying this patch, you can use this command to build it using clang.
<pre> CFLAGS="-w" CXXFLAGS="-w" cmake ../media-driver -DCMAKE_INSTALL_PREFIX=/usr -DMEDIA_VERSION="2.0.0" -DBS_DIR_GMMLIB=`pwd`/../gmmlib/Source/GmmLib/ -DBS_DIR_COMMON=`pwd`/../gmmlib/Source/Common/ -DBS_DIR_INC=`pwd`/../gmmlib/Source/inc/ -DBS_DIR_MEDIA=`pwd`/../media-driver -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ </pre>
> Fix compile issue on clang.

- Tools/MediaDriverTools/Android/GenerateAndroidMk.py
- Tools/MediaDriverTools/Android/mk/cmrt.tpl
- Tools/MediaDriverTools/Android/mk/gmm.tpl
- Tools/MediaDriverTools/Android/mk/media_driver.tpl
steps to generate Android.mk:
1. clone https://github.com/intel/gmmlib and https://github.com/intel/media-driver
2. put them in same directory under your android source directory, for example $android/vendor/intel/video/
3. install libva 2.0 on your host machine, we use it to grenerate linux makefile on host machine
4. call ./Tools/MediaDriverTools/Android/GenerateAndroidMk.py to generate Android.mk from linux makefile
5. lunch your android target, and make i965_drv_video
> andoird: add script to generate makefile for andorid

- CMakeLists.txt
- README.md
- Tools/bldsys/include/bs_dir_names.cmake
- distro_cmake.sh
- unified_cmake.sh
Fixes: #198  
- Default CMAKE_INSTALL_PREFIX to '/usr/local' but allow modifications at run-time
- Default MEDIA_VERSION / UFO_VERSION to 1.0.0
- Default gmmlib dependency paths until builds shift to dynamic linked
- Update README.md to reflect simplified build steps
- Update distro_cmake.sh & unified_cmake.sh scripts
Change-Id: I9250f6ff07c670a6cdf37ea516513b031508cabb
> Resolve 'provide a default building configuration'

- media_driver/linux/common/ddi/media_libva.cpp
libX11.so is a linker name so it is not available if the
libX11-dev package is not installed. As a result, attempting to
render to screen with X server will fail (e.g. sample_decode -r)
This fix changes the code to dlopen the actual library name
instead: libX11.so.6
The same patch has been applied to MediaSDK samples:
https://github.com/Intel-Media-SDK/MediaSDK/issues/210
And a similar issue was addressed in media-driver:
https://github.com/intel/media-driver/issues/150
> [ddi] Load libX11.so.6 instead of libX11.so

- media_driver/agnostic/gen9/hw/vdbox/mhw_vdbox_mfx_g9_X.h
The essential command buffer data for AVC encode should inlucde slice state,
ref index, weight offset, pak insert object. So mfx primitive command data size
should compose of their sizes.
Change-Id: Ia46b92578aa7903cca1a65c23d4ca06f1edd8cca
Signed-off-by: xiaominc <xiaomin.chen@intel.com>
> [Encode] Fix the mfx primitive command data size calculation for AVC encode

- media_driver/agnostic/common/codec/hal/codechal_encode_jpeg.cpp
- media_driver/agnostic/common/codec/hal/codechal_encode_jpeg.h
- media_driver/agnostic/common/codec/shared/codec_def_encode.h
- media_driver/linux/common/codec/ddi/media_ddi_encode_jpeg.cpp
- media_driver/linux/common/codec/ddi/media_ddi_encode_jpeg.h
- media_driver/linux/common/ddi/media_libva_caps.cpp
1. check whether the raw data include all of the headers, and provide different solution
2. when the packed data include all of the headers, scale the qmatrix for quality setting.
fix #111 #232
> Jpeg encode full packed header support 

- .travis.yml
switch to use intelmediadriver account
upgrade base image to 18.04
> use intelmediadriver faceless docker account

- media_driver/agnostic/common/codec/hal/codechal_encode_allocator.cpp
- media_driver/agnostic/common/codec/hal/codechal_encode_avc.cpp
- media_driver/agnostic/common/codec/hal/codechal_encode_csc_ds.cpp
- media_driver/agnostic/common/codec/hal/codechal_encode_hevc.cpp
- media_driver/agnostic/common/codec/hal/codechal_encode_tracked_buffer.cpp
- media_driver/agnostic/common/codec/hal/codechal_encode_tracked_buffer_hevc.cpp
- media_driver/agnostic/common/codec/hal/codechal_mmc_decode_hevc.cpp
- media_driver/agnostic/gen10/codec/hal/codechal_encode_csc_ds_g10.cpp
- media_driver/agnostic/gen10/codec/hal/codechal_vdenc_hevc_g10.cpp
- media_driver/agnostic/gen11/codec/hal/codechal_encode_csc_ds_g11.cpp
- media_driver/agnostic/gen9/codec/hal/codechal_encode_csc_ds_g9.cpp
- media_driver/agnostic/gen9/codec/hal/codechal_encode_hevc_g9.cpp
- media_driver/agnostic/gen9_skl/codec/hal/codechal_fei_hevc_g9_skl.cpp
Please ignore first two commits, it will be merged by https://github.com/intel/media-driver/pull/236
Please just review last commit(ef46047)
if you compile current driver like this
<pre>
CFLAGS="-Werror=parentheses -Werror=parentheses-equality -Wno-logical-op-parentheses -w" CXXFLAGS="-Werror=parentheses -Werror=parentheses-equality -Wno-logical-op-parentheses -w" cmake ../media-driver -DCMAKE_INSTALL_PREFIX=/usr -DMEDIA_VERSION="2.0.0" -DBS_DIR_GMMLIB=`pwd`/../gmmlib/Source/GmmLib/ -DBS_DIR_COMMON=`pwd`/../gmmlib/Source/Common/ -DBS_DIR_INC=`pwd`/../gmmlib/Source/inc/ -DBS_DIR_MEDIA=`pwd`/../media-driver -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++
</pre>
clang will complain about parentheses  things. 
It's reasonable since parentheses things are error-prone.
Plese consider …
> fix warning for -Wparentheses and -Wparentheses-equality on clang

- media_driver/linux/common/ddi/media_libva.cpp
- media_driver/linux/common/vp/ddi/media_libva_vp.h
Fix #201, add platform information in DdiMedia_QueryVideoProcPipelineCaps to distinguish Gen8 and Gen9+ max width and height
> [VP]Add platform information in DdiMedia_QueryVideoProcPipelineCaps

- README.md
Now driver could support HEVC/VP9 decode, HEVC VME/Low power encode, and
VP9 VME/low power encode in 8/10 bit.
> Update readme for ICL HEVC/VP9 encode/decode

- media_driver/linux/common/codec/ddi/media_ddi_decode_vp8.cpp
when the count in VABoolCoderContextVPX is zero, actually it means there are 8 bit in bool coder
correct first partition_size,when there is 8 bits in bool coder
> fix vp8 decode issue #190, change the first partition size

- media_driver/linux/common/codec/ddi/media_ddi_decode_base.cpp
Here is the case, when vaCreateBuffer() is called with source data
pointer provided, and there are multiple slices in the frame, buf->pData
is assigned a different buffer for the second or following slices if
bIsSliceOverSize is true, but the calling of mos_bo_subdata() for
the second slices would copy the data to the buffer of the first slice.
> [vaCreateBuffer] one fixing for issue in vaCreateBuffer().

- Tools/MediaDriverTools/Android/GenerateAndroidMk.py
Source is spelled incorrectly.
> Corrected spelling mistake.

- media_driver/agnostic/common/codec/hal/codechal_encode_avc_base.cpp
[Vdenc] Fix output stream is uncorrect at slice header's start code is 4 bytes on KBL.
Signed-off-by: zhizhen_tang <zhizhen.tang@intel.com>
> [Vdenc] Fix output stream is uncorrect at slice header's start code is 4 bytes on KBL.

- media_driver/linux/common/vp/ddi/media_libva_vp.c
Fix #272 , previously, color fill parameter will always be allocated, here add the condition when alpha channel of background color is not 0
> [VP]When alpha channel of background color is 0, will not do colorfill.

- CMakeLists.txt
set changing user environment through profile.d macros to false.
Users that want this should enable it on purpose
Fixes #348
Signed-off-by: Daniel Charles <daniel.charles@intel.com>
> build: do not modify user environment

- media_driver/linux/common/os/linux_skuwa_debug.h
cutils/log.h deprecated by google on android P
> android: replace deprecated cutils/log.h with log/log.h

- media_driver/linux/common/vp/ddi/media_libva_vp.c
VAProcDeinterlacingNone means bypass the deinterlace module, but now
give a error number and error message, change the logic with do nothing
for this mode.
> media_libva_vp: fix VAProcDeinterlacingNone handle issue.

- media_driver/agnostic/common/codec/hal/codechal_encode_hevc.cpp
- media_driver/agnostic/gen9/codec/hal/codechal_encode_hevc_g9.cpp
- media_driver/agnostic/gen9_bxt/codec/hal/codechal_encode_hevc_g9_bxt.cpp
- media_driver/agnostic/gen9_skl/codec/hal/codechal_encode_hevc_g9_skl.cpp
1. Make sure CODECHAL_HEVC_MBENC_PENC kernel state initialized.
2. Add support format for 10bit.
3. Make sure CODECHAL_HEVC_MBENC_DS_COMBINED kernel state initialized.
But need disable it on BXT and SKL. Check kernel size in
CodechalEncHevcStateG9::InitKernelStateMbEnc() instead of hard code.
Fixes #320.
> Fix HEVC 10bit encoding on KBL. (GitHub issue #320)

- media_driver/linux/common/ddi/media_libva_caps.cpp
Add VA_RT_FORMAT_Y420 8bit for VAProfileHEVCMain10.
> Fix VA_RT_FORMAT for VAProfileHEVCMain10.

- media_driver/agnostic/common/vp/hal/vphal_render_vebox_base.cpp
goto finish will use CmdBuffer, it will init later by VeboxSendVeboxCmd_Prepare
> VeboxSendVeboxCmd: do not goto finish if caller pass NULl for pRender

- media_driver/agnostic/common/codec/hal/codechal_mmc_decode_mpeg2.cpp
No need check the hwInterface  here
if hwInterface  is NULL, CodecHalMmcState::m_hwInterface will be null.
Many fuction calls will crash for release version(CODECHAL_HW_ASSERT is no op in release build)
> CodechalMmcDecodeMpeg2: follow other codec, do not check hwInterface for NULL

- media_driver/agnostic/common/codec/hal/codechal_encode_avc.cpp
- media_driver/agnostic/common/codec/shared/codec_def_common_encode.h
- media_driver/agnostic/common/codec/shared/codec_def_encode_avc.h
- media_driver/linux/common/codec/ddi/media_ddi_encode_avc.cpp
- media_driver/linux/common/codec/ddi/media_ddi_encode_avc.h
Enable max frame size feature for AVC encoder in legacy mode
> [Encode] Enable max frame size for AVC encoder legacy mode

- .travis.yml
- CMakeLists.txt
- README.md
- distro_cmake.sh
- media_driver/agnostic/gen10/codec/media_srcs.cmake
- media_driver/agnostic/gen10/vp/media_srcs.cmake
- media_driver/agnostic/gen11/codec/media_srcs.cmake
- media_driver/agnostic/gen11_icllp/codec/kernel/media_srcs.cmake
- media_driver/agnostic/gen11_icllp/codec/media_srcs.cmake
- media_driver/agnostic/gen11_icllp/vp/kernel/media_srcs.cmake
- media_driver/agnostic/gen8/codec/media_srcs.cmake
- media_driver/agnostic/gen8/vp/media_srcs.cmake
- media_driver/agnostic/gen9/codec/media_srcs.cmake
- media_driver/agnostic/gen9/vp/media_srcs.cmake
- media_driver/agnostic/gen9_bxt/codec/kernel/media_srcs.cmake
- media_driver/agnostic/gen9_bxt/codec/media_srcs.cmake
- media_driver/agnostic/gen9_kbl/codec/kernel/media_srcs.cmake
- media_driver/agnostic/gen9_kbl/codec/media_srcs.cmake
- media_driver/agnostic/gen9_skl/codec/media_srcs.cmake
- media_driver/cmake/linux/media_feature_flags_linux.cmake
- media_driver/linux/ult/ult_app/CMakeLists.txt
It was noted that FREE_KERNELS may be confusing since with =OFF it
actually enables non-free kernels (wihtout published sources). So,
let's use ENABLE_NONFREE_KERNELS instead.
Mind that ENABLE_NONFREE_KERNELS default value is ON. So, driver
default behaviour did not change.
Change-Id: Ifae417c3ada32d065fa615c9d5cc17c41f3b93b5
> build: change FREE_KERNELS option to ENABLE_NONFREE_KERNELS

- media_driver/cmake/linux/media_compile_flags_linux.cmake
- media_driver/linux/common/ddi/media_libva.cpp
- media_driver/linux/common/ddi/media_libva_common.h
- media_driver/linux/common/ddi/media_srcs.cmake
- media_driver/media_top_cmake.cmake
This is an updated version of the original PR #492
> Add X11 detect support

- media_driver/linux/common/ddi/media_libva.cpp
PR #494 set vaPutSurface as NULL, libva throws an error
and iHD driver is not initialized.
> Fix X11 detect support

- media_driver/agnostic/common/codec/hal/codechal_debug_config_manager.cpp
- media_driver/linux/common/codec/ddi/media_ddi_encode_vp8.cpp
DDI should parse frame rate buffer according to the definiton
of libva, not pass it directly to low level.
> [VP8] Implement frame rate in DDI according to interface

- media_driver/linux/common/ddi/media_libva.cpp
This makes the gst pipeline below works:
gst-launch-1.0 videotestsrc num-buffers=1 ! msdkvpp ! \
video/x-raw\(memory:DMABuf\),format=UYVY ! filesink location=a.yuv
Signed-off-by: Haihao Xiang <haihao.xiang@intel.com>
> Fix DeriveImage with UYVY fourcc

- media_driver/linux/common/os/i915/include/mos_bufmgr.h
- media_driver/linux/common/os/i915/include/uapi/README
- media_driver/linux/common/os/i915/include/uapi/drm.h
- media_driver/linux/common/os/i915/include/uapi/drm_fourcc.h
- media_driver/linux/common/os/i915/include/uapi/drm_mode.h
- media_driver/linux/common/os/i915/include/uapi/i915_drm.h
- media_driver/linux/common/os/i915/mos_bufmgr.c
- media_driver/linux/common/os/mos_os_specific.c
This will shut down the non-VME subslice on ICLLP when VME is used.
Fixes issue #267.
> Set subslice mask according to the per-context sseu value.

- media_driver/agnostic/common/hw/vdbox/mhw_vdbox_mfx_generic.h
- media_driver/agnostic/gen10/hw/vdbox/mhw_vdbox_mfx_g10_X.cpp
- media_driver/agnostic/gen8/hw/vdbox/mhw_vdbox_mfx_g8_X.h
- media_driver/agnostic/gen9/hw/vdbox/mhw_vdbox_mfx_g9_X.h
The original code tries to fix the encoding of the partition length fields too
late as the command has already been written to the command stream. The command
encoding is the same for different gens so the fix can be  implemented in the
generic encoding of the command. This patch fixes some of the GPU hangs when
decoding VP8 streams.
> [Decode] Fix partition lengths for MFD_VP8_BSD_OBJECT commands.

- CMakeLists.txt
cmake install as PROGRAMS will set the proper permissions
to iHD_drv_video.so file to be 755 in linux
Fixes #215
Signed-off-by: Daniel Charles <daniel.charles@intel.com>
> installing:  install driver with proper permissions

- media_driver/linux/common/os/i915/mos_bufmgr.c
In a dual GPU system, it is possible to open a non-Intel GPU device node then try to use iHD driver.  See https://gitlab.freedesktop.org/gstreamer/gstreamer-vaapi/issues/135 for details.
> Don't create the GEM buffer manager for invalid device

- media_driver/linux/common/ddi/media_libva.cpp
When destroy bitstream buffer, it should decrease
bufMgr->dwNumSliceData.
> Keep the right slice number for bitstream buffer.

- .travis.yml
Always build latest libva to avoid use the docker image libva to keep sync.
> Travis: Add libva build step

- .travis.yml
Add DLIBVA_DRIVERS_PATH and DLIBVA_INSTALL_PATH to make sure driver in
docker image use the correct libva lib.
> Travis: add libva path in build

- media_driver/linux/common/ddi/media_libva_caps.cpp
> [RFC] Add VA_RC_MB flag for VAEntrypointEncSliceLP+HEVC encoding.

- media_driver/linux/common/ddi/media_libva.cpp
> add Y410 image change for CreateImage

- media_driver/linux/common/codec/ddi/media_libva_decoder.cpp
There was an instance where the X11_FOUND flag was missing
causing build failures on systems which do not support X(eg. chrome).
Fix this by adding the check.
> Add X11_FOUND flag

- media_driver/linux/common/ddi/media_libva_caps.cpp
- media_driver/linux/gen11/ddi/media_libva_caps_g11.cpp
it never used on android any more, we will use dma buf
@tchew6 , please help review this
> libva_caps: remove unused VA_SURFACE_ATTRIB_MEM_TYPE_ANDROID_GRALLOC

- media_driver/linux/common/codec/ddi/media_ddi_encode_avc.cpp
Fix the if-else logic in DdiEncodeAvc::ParseMiscParamQuantization(),
otherwise driver will report ASSERTMESSAGE even if the situation is
valid.
Refine the code stye.
> media_ddi_encode_avc: fix the if-else logic and code style

- media_driver/linux/common/os/mos_defs_specific.h
Alternative definition for CONCAT which is not defined by musl.
> linux: fix build when using musl

- media_driver/agnostic/common/codec/hal/codechal_encode_avc_base.cpp
- media_driver/agnostic/common/codec/shared/codec_def_common_avc.h
in case the application input the level idc 9, add flag "CODEC_AVC_LEVEL_1b" to support it.
> [AVC Encode] add level_idc CODEC_AVC_LEVEL_1b

- media_driver/agnostic/common/codec/hal/codechal_decoder.cpp
no clear description of the meaning of the value for jpeg
just the description for AVC MPEG2 ... so, ignore it
> ignore error status value for jpeg decode

- media_driver/agnostic/common/cm/cm_hal.cpp
- media_driver/agnostic/common/cm/cm_hal.h
- media_driver/agnostic/common/cm/cm_queue_rt.cpp
- media_driver/agnostic/common/cm/cm_queue_rt.h
- media_driver/linux/common/cm/cm_hal_os.cpp
- media_driver/linux/common/ddi/media_libva_common.cpp
Ignore special surfaceID value VA_INVALID_SURFACE.
GetSurfaceFromVASurfaceID may be called
for non existing reference frame,
e.g., for Intra-only frame with surfaceID = -1.
The caller validates the surface again,
fix non-existing reference,
and decoding proceeds without any problem.
But the driver reports about critical error constantly.
> Fix SurfaceFromID get rid of false alarm

- media_driver/linux/common/ddi/media_libva.cpp
- media_driver/linux/common/ddi/media_libva_util.cpp
- media_driver/linux/common/os/media_srcs.cmake
- media_driver/linux/common/os/mos_sw_swizzle.c
- media_driver/linux/common/os/mos_sw_swizzle.h
- media_driver/linux/gen11/ddi/media_sku_wa_g11.cpp
Use sw swizzling since gtt map is very slow on gen11.
The swizzling code has been borrowed from mesa Intel Surface Layout library
Signed-off-by: Dmitry Ermilov <dmitry.ermilov@intel.com>
> Use sw swizzling on Gen11

- media_driver/linux/common/ddi/media_libva_caps.cpp
- media_driver/linux/gen11/ddi/media_libva_caps_g11.cpp
Use VP9 max resoltuion (8K) instead of default max resolution (4K).
> Fix VP9 8K decoding.

- media_driver/agnostic/common/codec/hal/codechal_encode_vp8.cpp
- media_driver/linux/common/codec/ddi/media_ddi_encode_vp8.cpp
1. Initialize BRC variales for avoiding wrong DSH allocation.
2. Set the right CQP enum number (RATECONTROL_CQP = 3).
3. Avoid division by zero in CQP mode.
Fixes #578.
> Fix VP8 CQP encoding.

- media_driver/linux/common/codec/ddi/media_ddi_encode_avc.cpp
- media_driver/linux/common/codec/ddi/media_ddi_encode_avc.h
- media_driver/linux/common/codec/ddi/media_ddi_encode_base.cpp
- media_driver/linux/common/codec/ddi/media_ddi_encode_base.h
> Add free logic of picParams->pDeltaQp for avoiding memory leak.

- media_driver/agnostic/common/vp/hal/vphal_renderer.cpp
- media_driver/linux/gen9/ddi/media_sku_wa_g9.cpp
BXT support P010 output. Decoded hevce 10b output sreams from BXT and CFL
are bit2bit.
> Enable supporting p010 output on BXT

- media_driver/linux/common/ddi/media_libva.cpp
- media_driver/linux/common/ddi/media_libva_util.h
Two concurrent DdiMedia_SyncSurface function calls read and
write the same data when the second frame uses the first frame
as a reference frame.
> [Decode] Prevent mt read/write conflict

- media_driver/linux/common/codec/ddi/media_libva_encoder.cpp
- media_driver/linux/common/ddi/media_libva_caps.cpp
- media_driver/linux/common/ddi/media_libva_caps.h
- media_driver/linux/common/ddi/media_libva_common.h
- media_driver/linux/gen11/ddi/media_libva_caps_g11.cpp
- media_driver/linux/gen11/ddi/media_libva_caps_g11.h
This change aims to replace member FeiFunction of 'global' DDI_MEDIA_CONTEXT class
with retrieving fei function type from provided vaConfig.
Old implementation had a race condition bug when e.g. PREEnc and AVC FEI encode
are created simultaneously from two threads.
Fixes #590
Signed-off-by: Dmitry Ermilov <dmitry.ermilov@intel.com>
> [Encode] Fix for race condition in AVC FEI

- media_driver/linux/common/os/i915/include/mos_bufmgr.h
- media_driver/linux/common/os/i915/include/uapi/drm.h
- media_driver/linux/common/os/i915/include/uapi/drm_mode.h
- media_driver/linux/common/os/i915/include/uapi/i915_drm.h
- media_driver/linux/common/os/i915/mos_bufmgr.c
- media_driver/linux/common/os/mos_context_specific.cpp
- media_driver/linux/common/os/mos_gpucontext_specific.cpp
- media_driver/linux/common/os/mos_gpucontext_specific.h
- media_driver/linux/common/os/mos_os_specific.c
- media_driver/linux/gen11/ddi/media_sku_wa_g11.cpp
- media_driver/linux/ult/libdrm_mock/mos_bufmgr_mock.c
- media_driver/linux/ult/libdrm_mock/xf86drm_mock.c
To enable virtual engine for Gen11.
> Enable virtual engine (single pipe) on Gen11.

- media_driver/linux/common/os/mos_gpucontext_specific.cpp
Avoid pAttriVe access invalid memory area.
> Fix command buffer initialization for virtual engine.

- media_driver/linux/common/ddi/media_libva_caps.cpp
> 8K resolution size is only for HEVC not for AVC and VP9.

- media_driver/linux/common/ddi/media_libva_caps.cpp
- media_driver/linux/gen10/ddi/media_libva_caps_g10.cpp
- media_driver/linux/gen11/ddi/media_libva_caps_g11.cpp
- media_driver/linux/gen9/ddi/media_libva_caps_g9.cpp
> Add A2RGB10 and A2BGR10 format in vaQueryImageFormats.

- media_driver/agnostic/common/codec/hal/codechal_encoder_base.cpp
It will cause error in drm IO Ctrl.
> Avoid disable half of sub slices if only one sub slice.

- media_driver/linux/common/codec/ddi/media_ddi_encode_avc.cpp
> Avoid invalid max/min qp for AVC encoding.

- media_driver/agnostic/common/vp/hal/vphal_renderer.cpp
m_reporting is initialized in constructor as nullptr:
https://github.com/intel/media-driver/blob/baa8b1f7a8b903abdf0e8ad9882773752b120262/media_driver/agnostic/common/vp/hal/vphal_renderer.cpp#L1665
Hence, we should assume that it may fail to be initialized later on and protect the code at least in the destructor:
https://github.com/intel/media-driver/blob/baa8b1f7a8b903abdf0e8ad9882773752b120262/media_driver/agnostic/common/vp/hal/vphal_renderer.cpp#L1443
This will be a real segmentation fault on the on-screen rendering attempt if driver will be built with ENABLE_NONFREE_KERNELS=OFF and at least DRI2 rendering path will be selected.
> vp: avoid segfault on Linux if vp failed to initialize

- media_driver/agnostic/common/vp/hal/vphal_renderer.cpp
- media_driver/linux/gen9/ddi/media_sku_wa_g9.cpp
Tested vpp with p010 output. Output streams are valid and they show good
metrics. All gen9 platforms support p010 output.
> Enable supporting p010 output on SKL

- media_driver/linux/common/ddi/media_libva_caps.cpp
> Add VAConfigAttribMaxFrameSize query support for AVC encoding.

- media_driver/linux/common/cm/cm_wrapper_os.cpp
- media_driver/linux/common/codec/ddi/media_libva_decoder.cpp
- media_driver/linux/common/codec/ddi/media_libva_encoder.cpp
> Set MOS GmmClientContext locally for avoiding wrong pointer.

- media_driver/linux/common/ddi/media_libva_caps.cpp
change distinguish VA_STATUS_ERROR_INVALID_VIDEO_PARAMETER
with VA_STATUS_ERROR_UNSUPPORTED_PROFILE and
VA_STATUS_ERROR_UNSUPPORTED_ENTRYPOINT
> Correct error code returned from VAGetConfigAttributes

- media_driver/linux/common/codec/ddi/media_ddi_encode_avc.cpp
When min QP is set but Max Qp is zero, need use Maximum QP (51) as Max
QP.
Fixes #587.
> Avoid invalid Max QP when AVC encoding.

- media_driver/linux/common/ddi/media_libva.cpp
Exporting P010 buffers fails because we don't recognize it as a
composite object. Add DRM_FORMAT_P010 as a return value for
VA_FOURCC_P010.
Signed-off-by: Harish Krupo <harishkrupo@gmail.com>
> media_libva: Return P010 as a composite format

- media_driver/linux/gen9_skl/ddi/media_libva_caps_g9_skl.cpp
According to media-driver readme, SKL doens`t support HEVC 10b encoding,
but media-driver has incorrect report. Same situation for VP9.
fixes #693
> [Encode] Fix caps report for HEVC/VP9 on SKL

- media_driver/linux/common/ddi/media_libva_caps.cpp
- media_driver/linux/gen11/ddi/media_libva_caps_g11.cpp
> Add VASurfaceAttribMemoryType query for decoding/encoding.

- media_driver/cmake/linux/media_compile_flags_linux.cmake
Drop " -Werror=implicit-function-declaration"  flag.Since gcc9 ,this error flag only makes sense for C code.
fixes #712
> Drop one compile flag for gcc9

- media_driver/agnostic/common/codec/hal/codechal_decode_vp8.cpp
- media_driver/agnostic/common/codec/shared/codec_def_decode.h
- media_driver/linux/common/codec/ddi/media_ddi_decode_vp8.cpp
- media_driver/linux/common/codec/ddi/media_ddi_decode_vp8.h
the fix should be exist in ffmpeg
it is another solution. ffmpeg use the surface which is decoded by other
context to be reference. so need to register it
> register VP8 decode reference frame

- media_driver/linux/common/codec/ddi/media_ddi_encode_avc.cpp
- media_driver/linux/common/codec/ddi/media_ddi_encode_avc.h
AVC VDENC when multi-slice encoding need force first_mb_in_slice to 0.
Fixes #389.
> Adjust packed slice header for AVC VDENC when multi-slice encoding.

- media_driver/linux/common/vp/ddi/media_libva_vp.c
According to the documentation[1], user may provide an array
which can't hold all filter caps, so the driver must check the
the number of elements in the input array, otherwise it might
result in invalid write
Issue can be catched by the command below:
valgrind gst-launch-1.0 videotestsrc ! video/x-raw,width=720,height=480 !
vaapipostproc video-direction=90r ! vaapisink
==25222== Invalid write of size 4
==25222==    at 0x946197A:
DdiVp_QueryVideoProcFilterCaps(VADriverContext*, unsigned int, int,
void*, unsigned int*) (media_libva_vp.c:4100)
==25222==    by 0x93FF773:
DdiMedia_QueryVideoProcFilterCaps(VADriverContext*, unsigned int,
_VAProcFilterType, void*, unsigned int*) (media_libva.cpp:5646)
==25222==    by 0x6D19641: vaQueryVideoProcFilterCaps (va.c:2183)
==25222==    by 0x6C3A530: …
> Avoid invalid write in media_libva_vp.c

- media_driver/linux/common/codec/ddi/media_ddi_encode_mpeg2.cpp
Use vbvBuf in 16kb to match the behaviour in SetCurbeBrcInitReset()
to generate the correct m_bufSizeInBits.
Discard the default CBR mode to enable the setting for VBR.
Fix the issue in FFmpeg trac #7650 in driver level
> encode_mpeg2: use 16kb as the buf unit for mpeg2 vbvBuf

- media_driver/linux/gen12/ddi/media_sysinfo_g12.cpp
TGL Device ID synced with public linux kernel upstream:
* https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/include/drm/i915_pciids.h?h=v5.4-rc7#n590
Change-Id: Ice7dfa1087e5089ae37428448af6b8463b21633e
> tgl: sync linux device id list with kernel upstream

- media_driver/agnostic/gen12/cm/cm_hal_g12.cpp
- media_driver/agnostic/gen12/codec/hal/codechal_encode_csc_ds_g12.cpp
- media_driver/agnostic/gen12/codec/hal/codechal_vdenc_avc_g12.cpp
- media_driver/agnostic/gen12/codec/hal/codechal_vdenc_vp9_g12.cpp
- media_driver/agnostic/gen12_tgllp/vp/media_srcs.cmake
Fixes: #786
This fixed -DENABLE_KERNELS=OFF build mode if kernels will be physically
removed from the repository.
> gen12: fix -DENABLE_KERNELS=OFF build mode w/ removed kernels

- media_driver/linux/gen9/ddi/media_sku_wa_g9.cpp
- media_driver/linux/gen9/ddi/media_sysinfo_g9.cpp
* UHD Graphics 500 / 600 are 12 EU GT1 SKUs
* UHD Graphics 505 / 605 are 18 EU GT1.5 SKUs
This also changes 18 EU SKUs to be treated as GT 1.5.
I've also added `0x0a84` as BXT 18 EU device based on [i965_pci_ids.h](https://gitlab.freedesktop.org/mesa/mesa/blob/master/include/pci_ids/i965_pci_ids.h) from mesa.
> Fix device info for GT1 BXT / GLK SKUs

- docs/media_features.md
just verified gen9 hevc 4k encoder, so change the max resolution to 4k
> change media_features.md about resolution of Gen9 hevc encode

- media_driver/agnostic/gen11/hw/vdbox/mhw_vdbox_hcp_g11_X.cpp
- media_driver/agnostic/gen12/hw/vdbox/mhw_vdbox_hcp_g12_X.cpp
Current HW cannot support HEVC stream with
cabac_bypass_alignment_enabled_flag == 1.
> Check cabac_bypass_alignment_enabled_flag.

- media_driver/linux/common/ddi/media_libva_caps.cpp
related libva change: https://github.com/intel/libva/pull/220
> add prediction direction caps for AVC VDEnc

- media_driver/linux/common/codec/ddi/media_ddi_decode_vp8.h
- media_driver/linux/common/codec/ddi/media_ddi_decode_vp9.h
VPX decoding should not use DPB mode in DdiMediaBase::ClearRefList().
Otherwise, the reference surface may be overwritten wrong.
> Disable DPB mode for VPX.

- media_driver/linux/common/os/mos_util_debug_specific.c
The return value of MOS_SecureStringPrint is the number of characters printed.
> [MOS] correct the use of the return value of MOS_SecureStringPrint

- media_driver/agnostic/common/os/mos_utilities.h
array used as initializer
fixes #736
> Fix Build fail under CentOS7.6 with its native gcc 4.8 compiler

- README.md
TGL doesn't support VP8, need to remove related description from README
> remove VP8 description of TGL from README

- media_driver/linux/gen10/ddi/media_libva_caps_g10.cpp
- media_driver/linux/gen11/ddi/media_libva_caps_g11.cpp
- media_driver/linux/gen12/ddi/media_libva_caps_g12.cpp
- media_driver/linux/gen8/ddi/media_libva_caps_g8.cpp
- media_driver/linux/gen9/ddi/media_libva_caps_g9.cpp
It is the requirement of VA-API
See https://github.com/intel/libva/blob/master/va/va.h#L1187-L1194
> Set the value for unknown or unsupported attributes to VA_ATTRIB_NOT_SUPPORTED

- media_driver/linux/gen12/ddi/media_libva_caps_g12.cpp
Otherwise the driver only advertises 1920x1920 VP9 encoding on GEN12
Refer to
https://gitlab.freedesktop.org/gstreamer/gstreamer-vaapi/issues/229 for
issue details
> Support up to 8Kx8K VP9 encoding on GEN12

- media_driver/linux/common/ddi/media_libva_caps.cpp
Add VA_ENC_SLICE_STRUCTURE_ARBITRARY_ROWS for VAEntrypointEncSliceLP.
Fix #805.
Not sure whether it's proper to fix like this, please help to comment.
> media_libva_caps: add VAConfigAttribEncSliceStructure caps for VAEntrypointEncSliceLP

- media_driver/linux/common/ddi/media_libva_caps.cpp
According to: https://github.com/intel/media-driver/blob/master/docs/media_features.md
Also in [MediaLibvaCaps::CheckEncodeResolution](https://github.com/intel/media-driver/blob/2711a3a1c3339b1a5f5d5e1c76fccd24f1998d81/media_driver/linux/common/ddi/media_libva_caps.cpp#L1954) function we check the max size as 4k.
Fixes #550
Signed-off-by: egorovdanil <danil.egorov@intel.com>
> [Encode][HEVC] Fix max width and height caps for gen9 platforms

- media_driver/agnostic/gen12/codec/hal/codechal_decode_vc1_g12.cpp
This is a copy of commit 18457ca9
Refer to https://gitlab.freedesktop.org/gstreamer/gstreamer-vaapi/issues/220 for
issue details
> Fix VC1 decode output corruption on GEN12

- media_driver/linux/gen12/ddi/media_sku_wa_g12.cpp
WaSuperSliceHeaderPacking is still needed for AVC VDEnc on GEN12, otherwise the output is
corrupted if the first 4 bytes is '00 00 00 01' in the packed slice header.
example:
gst-launch-1.0 videotestsrc num-buffers=500 ! video/x-raw,format=NV12 !
vaapih264enc tune=low-power ! filesink location=output.h264
Fixes https://github.com/intel/media-driver/issues/853
> Enable the WA for slice header insertion on GEN12

- media_driver/linux/common/codec/ddi/media_ddi_encode_vp9.cpp
Without a flag, user doesn't know VACodedBufferSegment.next pointing
to a private segment status, so we have to ignore this private
status buffer. Otherwise it will result in segmentation fault if user
takes VACodedBufferSegment.next as a VACodedBufferSegment pointer
Example:
gst-launch-1.0 videotestsrc !
video/x-raw,format=NV12,width=3840,height=2160 ! vaapivp9enc !
matroskamux ! filesink location=output.vp9
> Ignore the private VP9 status buffer

- media_driver/linux/gen11/ddi/media_libva_caps_g11.cpp
Based on docs/media_features.md, the Max Res supported for ICL is 4K.
Same support in common media_libva_caps:
https://github.com/intel/media-driver/blob/master/media_driver/linux/common/ddi/media_libva_caps.cpp#L2640
> media_libva_caps_g11: add max resolution support for vp8 encode

- media_driver/agnostic/common/codec/hal/codechal_debug.cpp
It should not be height*2 because one pixel only occupies DWORD.
> Fix Y410 YUV dump.

- media_driver/linux/common/ddi/media_libva_util.cpp
- media_driver/linux/common/os/mos_graphicsresource_specific.cpp
Perf will drop from 25fps to 10fps for 1080p decode + vp(nv12tileY -> i420linear) if only mos_gem_bo_map_gtt(surface->bo) on AtomSOC(APL).
> Fix the performance issue on APL.

- media_driver/agnostic/gen10/codec/hal/codechal_encode_vp8_g10.cpp
- media_driver/agnostic/gen11/codec/hal/codechal_encode_vp8_g11.cpp
- media_driver/agnostic/gen9/codec/hal/codechal_encode_vp8_g9.cpp
Ensure the submission of forced_lf_adjustment in mode probablity
update kernel curbe for gen9, gen10 and gen11.This will help to fix
the ffmpeg decoder output md5 mismatch with vpxdec for
the Intel encoded video samples.
Reported, Tested and Verified by Hirokazu Honda<hiroh@google.com>
> Encoder: VP8: GEN9/GEN10/GEN11: Ensure forced_lf_adjustment update in media kernel

- media_driver/agnostic/common/vp/hal/vphal_render_sfc_base.cpp
SFC can support bottom color-fill on Gen12, use SFC to handle such scenario if no scaling needed when set ScalingPreference as COMP.
> [VP] Fix #843

- media_driver/agnostic/common/codec/hal/codechal_decode_avc.h
- media_driver/agnostic/common/os/mos_utilities.c
- media_driver/agnostic/common/renderhal/renderhal.cpp
- media_driver/agnostic/gen11/codec/hal/codechal_huc_cmd_initializer_g11.h
Fixes: #879
This fixes:
* -Wnon-c-typedef-for-linkage
* -Wsizeof-array-div
* -Wrange-loop-construct
Change-Id: I0d081070ce5abb4c707af767330141eb87748065
> clang-10/11: fix compilation issues

- media_driver/linux/gen11/ddi/media_libva_caps_g11.cpp
Fix the HEVC 422 10-bit encoding for FFmpeg vaapi.
> media_libva_caps_g11: add caps query support for Y210 in VAEntrypointEncSlice

- media_driver/linux/common/os/i915/xf86drm.c
- media_driver/linux/ult/libdrm_mock/xf86drm_mock.c
Fixes: #870
With upcoming gcc-10 we start to see Werror=format-overflow reporting
that we attempt to printf %s null strings.
Change-Id: I7a62bc98bf7dd6bcd61d475d7650a06aa1a70932
> build: fix Werror=format-overflow under gcc-10

- media_driver/linux/gen12/ddi/media_libva_caps_g12.cpp
Without this setting, user application will fail to decode HEVC 8/10 bits 444 videos
Sample pipeline:
gst-launch-1.0 filesrc location=input.10bit.444.h265 ! h265parse ! vaapih265dec ! fakesink
Fixes https://github.com/intel/media-driver/issues/882
> Gen12: Set correct value for VAConfigAttribRTFormat for HEVC main-444 and main-444-10

- media_driver/linux/common/ddi/media_libva.cpp
should apply similiar changes for other planar format in near future
it is quick fix for chromium encoding issue
> use gmmlib caculate the NV12 surface offset

- media_driver/linux/common/ddi/media_libva_caps.cpp
This reverts commit 11fd7a1d0fa5dd8ca00fd3241f3364279e8d5251.
> Revert "media_libva_caps: add VAConfigAttribEncSliceStructure caps for VAEntrypointEncSliceLP"

- media_driver/agnostic/common/vp/kdll/hal_kerneldll.c
When KernelDll_BuildKernel_CmFc() calls cm_fc_combine_kernels()
(see [1]), one of the inputs is &dwEstimatedKernelSize.  It is a
uint32_t pointer but is typecasted to a size_t pointer.
On platforms where size_t is a 64-bit integer, subsequent write
operations using this size_t pointer results in 4 bytes of
memory corruption.
[1] https://github.com/intel/media-driver/blob/master/media_driver/agnostic/common/vp/kdll/hal_kerneldll.c#L5045
> [VP] Fix memory corruption

- media_driver/linux/gen12/ddi/media_libva_caps_g12.cpp
Remove VA_ENC_SLICE_STRUCTURE_ARBITRARY_ROWS from it.
It was reverted from MediaLibvaCaps::CreateEncAttributes()
as e90d17e5, align with it.
> media_libva_caps_g12: update VAEntrypointEncSliceLP

- media_driver/agnostic/gen12/codec/hal/codechal_decode_hevc_g12.cpp
- media_driver/agnostic/gen12/codec/hal/codechal_decode_hevc_long_g12.cpp
- media_driver/agnostic/gen12/codec/hal/codechal_decode_scalability_g12.cpp
- media_driver/agnostic/gen12/codec/hal/codechal_decode_scalability_g12.h
- media_driver/linux/common/codec/ddi/media_ddi_decode_hevc.cpp
- media_driver/linux/gen12/codec/ddi/media_ddi_decode_hevc_g12.cpp
Real tile decoding depends on subset parameters. It will result in GPU
hang if user doesn't provide subset parameters.
Example:
gst-launch-1.0 filesrc location=input.tile.h265 ! h265parse ! \
vaapih265dec ! fakesink
> GEN12: HEVC: Don't enable real tile if no subset parameters on Linux

- media_driver/linux/common/ddi/media_libva.cpp
- media_driver/linux/common/ddi/media_libva_common.h
This patchset fixed some memory leak in the driver.
> media_libva: Fix memory leak

- media_driver/agnostic/common/vp/hal/vphal.cpp
- media_driver/agnostic/common/vp/hal/vphal_renderer.h
The maxSrcRect member keeps track of the maximum rectangle
among a set of source surfaces.  There is a need to
explicitly re-initialize this member in VphalState::Render
prior to calling the main render function.  This is so that
the maxSrcRect value for the last set of surfaces does not
get re-used for the current set of surfaces.
This fixes https://github.com/intel/media-driver/issues/905.
> [VP] Explicitly initialize maxSrcRect of VphalRenderer

- media_driver/linux/common/ddi/media_libva.cpp
Fix issue #916. Some formats like 444P/422V/422H can be supported as input for VP, but cannot be supported as output, thus cannot always use vp to do a conversion in GetImage.
> [VP] Add condition to use VP in GetImage

- media_driver/linux/common/codec/ddi/media_ddi_decode_vp8.cpp
fixes vp8 decoding crash in chromeos,
ffmpeg 4.2 vp8 decoding works fine
in kbl/cml/jsl 
fixes #910
> [VP] fix crash in vp8 playback.

- media_driver/linux/common/ddi/media_libva.cpp
- media_driver/linux/common/ddi/media_libva_common.h
While debugging an issue, I noticed that we go inside the if in [1] which indicates an invalid condition. The problem is that DdiMedia_Terminate() unconditionally unloads CP lib, even when loading it fails. My proposed solution is to keep track of whether the CP lib was loaded on DdiMedia__Initialize() in order to decide if it needs to be unloaded on DdiMedia_Terminate().
[1] https://github.com/intel/media-driver/blob/7b4f9c93c8a0825ce1e8d9ab45d06f9e887a7150/media_driver/linux/common/cp/shared/cplib_utils.cpp#L136-L140
> [CP] Unload CP lib only if it was loaded.

- media_driver/linux/common/ddi/media_libva_caps.cpp
- media_driver/linux/gen12/ddi/media_libva_caps_g12.cpp
ICQ mode isn't supported by HEVC VDENC.
Fixes #618.
> Disable ICQ mode for HEVC VDENC.

- media_driver/agnostic/gen10/hw/vdbox/mhw_vdbox_hcp_g10_X.cpp
- media_driver/agnostic/gen11/hw/vdbox/mhw_vdbox_hcp_g11_X.cpp
- media_driver/agnostic/gen12/hw/vdbox/mhw_vdbox_hcp_g12_X.cpp
- media_driver/agnostic/gen9_bxt/hw/vdbox/mhw_vdbox_hcp_g9_bxt.cpp
- media_driver/agnostic/gen9_kbl/hw/vdbox/mhw_vdbox_hcp_g9_kbl.cpp
We have been seeing random gpu hang on various devices while decoding 4k
VP9 streams. This patch is addressing a couple of issues which is expected
to fix the hangs:
a) The current code tries to reset SegmentIDStreamIn if there is
a resolution change on inter-frames. But due to the mishandling,
the code was eventually setting SegmentIDStreamIn to true for all
non-scaling use cases. The patch ensures that the reset happens
only for res-change on P-frames irrespective of other conditions.
b) The current implementation sets the SegmentIDStreamIn for any
decode where there is no Segmentation Enabled. We rather follow
strict constraints similar to the legacy i965 implementation.
c) Ensure the correct SegmentIDStreamIn for key-frames, intra-only
frames and error-resilient mode.
d) Reset …
> Decoder:VP9:GEN{9,10,11,12} : Fix the GPU hang due to wrong SegmentIDStreamIn & UsePrevInFindMvReferences

- media_driver/agnostic/gen10/renderhal/renderhal_g10.cpp
- media_driver/agnostic/gen11/renderhal/renderhal_g11.cpp
- media_driver/agnostic/gen12/renderhal/renderhal_g12.cpp
- media_driver/agnostic/gen9/renderhal/renderhal_g9.cpp
- media_driver/linux/common/os/mos_os_specific.c
mos_os_specific.c: "DestroyIPC(perStreamParameters)" is undefined when IPC
is disabled after applying 0002-Disable-IPC-usage.patch
renderhal_gxx.cpp: Result of comparison of constant 8 in expression
"pRenderHalSurface->Rotation < 8" will always be true.
Replace the constant with a predefined enumerated type.
Signed-off-by: Michele Lim <michele.lim@intel.com>
> Fix renderhal and MOS-specific compile errors.

- media_driver/linux/common/ddi/media_libva.cpp
For advanced DI, the reported capability of backward reference number should be 1. Fix #640
> [VP] Correct reference number in caps

- media_driver/linux/common/codec/ddi/media_ddi_encode_hevc.cpp
- media_driver/linux/common/ddi/media_libva_common.cpp
- media_driver/linux/common/ddi/media_libva_common.h
replace the reconstruct surface to be variant surface for HEVC REXT encoding
it could make the difference between recon/raw to be transparent to application
pay attention , the surface should be not read or write.
it is part of #915  to facilitate the test separately 
> replace the reconstruct surface to be variant

- media_driver/linux/gen12/ddi/media_libva_caps_g12.cpp
Otherwise user application cannot get the right attributes and will fail
to support SCC main 444 and main 10 decoding
> media_libva_caps_g12: create decoding attributes for SCC main 444 and main 10

- media_driver/linux/gen12/codec/ddi/media_ddi_decode_hevc_g12.cpp
- media_driver/linux/gen12/ddi/media_libva_caps_g12.cpp
VA-API has already defined VAProfileHEVCSccMain444_10 for scc-main444-10,
so we should use VAProfileHEVCSccMain444_10 instead of
VAProfileHEVCSccMain444, otherwise user doesn't know scc-main444-10 is
supported when querying the driver's capabilities
> media_libva: Fix scc-main444-10 decoding

- media_driver/linux/common/vp/ddi/media_libva_vp.c
Fix colorspace missing for some format in DdiVp_GetColorSpaceFromMediaFormat. Fix #929
> [VP] Fix colorspace missing for some formats

- media_driver/linux/gen11/ddi/media_libva_caps_g11.cpp
Fix encoding recon surface issue for Y210.
> media_libva_caps_g11: Add missing Y216 GMM format support for gen11

- media_driver/linux/common/ddi/media_libva.cpp
- media_driver/linux/common/ddi/media_libva.h
Add driver DDI side vaSyncSurface2 implementation with timeout.
Modify vaSyncSurface to share same status check function after bo_wait.
Fixes #932
> vaSyncSurface2 driver implementation

- media_driver/linux/common/ddi/media_libva_caps.cpp
VAConfigAttribRateControl supports VA_RC_QVBR at
VAEntrypointEncSlice.
This fixes a regression introduced by
```
commit 296ad00146499e6aecb247a2cb0fdef09b64bce1
Author: ShawnLi <shawn.li@intel.com>
Date:   Thu Apr 2 15:01:17 2020 +0800
[Encode] fix rate control caps issue
VAConfigAttribRateControl do not support VA_RC_QVBR
at VAEntrypointEncSliceLP before gen12
```
Fixes #918
> [Encode] fix hevc QVBR BRC caps regression

- media_driver/linux/gen11/codec/ddi/media_ddi_decode_hevc_g11.cpp
- media_driver/linux/gen12/codec/ddi/media_ddi_decode_hevc_g12.cpp
> Add checking for avoid mismatched size of HEVC slice parameter.

- media_driver/agnostic/gen9_kbl/hw/vdbox/mhw_vdbox_hcp_g9_kbl.cpp
Without having the HprVp9ModeSwitchEco disabled, the gen9 devices
cause gpu to hang while decoding tiled 4k vp9 streams for a
longer period. This particular chicken bit has been set in the
legacy i965 driver to avoid random gpu hangs.
Fixes #974
> Decoder: VP9: GEN9: Disable HPR VP9 mode switch to avoid GPU hang

- media_driver/linux/gen12/ddi/media_libva_caps_g12.cpp
> Add NV12 format for HEVCSccMain444 based on the standard.

- media_driver/linux/common/os/hwinfo_linux.h
GLK has no LLC, need use map_gtt to access data
> add GLK to IS_ATOMSOC check list

- media_driver/linux/gen12/ddi/media_libva_caps_g12.h
This change will remove 422 RTFormats support from TGL to fix incorrect surface configuration.
> [Encode] Removing 422 RTFormat support from VP9 VDEnc in TGL

- media_driver/linux/gen12/ddi/media_sku_wa_g12.cpp
Otherwise user will be misled by the output of vainfo on Linux
Change-Id: I039fdea492db884a53d24ae8966c619c714e7a96
> media: don't advertise AV1 decoding if the platform doesn't support it

- media_driver/linux/common/ddi/media_libva.cpp
to make sure media-driver could build with latest libva release
and libva master branch
> add version check for new version api support

- media_driver/agnostic/common/os/mos_resource_defs.h
ffmpeg-vaapi convert AYUV to other formats need
to determine whether the input format is YUV or RGB.
So I add Format_AYUV to IS_YUV_FORMAT(format)
to make sure that AYUV is treated as YUV.
Signed-off-by: Zhang yuankun <yuankunx.zhang@intel.com>
> [vpp] add Format_AYUV to IS_YUV_FORMAT(format)

- media_driver/linux/gen12/codec/ddi/media_ddi_decode_av1_g12.cpp
- media_driver/linux/gen12/codec/ddi/media_ddi_decode_av1_g12.h
Now only "1 slice data buffer(with N slices data in it) + 1 slice
param buffer(with N slices params in it)" support. So add the
support for multi slices data and slices params buffers.
Signed-off-by: Fei Wang <fei.w.wang@intel.com>
> [Decode] Add multi slice data/params buffers support for AV1

- media_driver/linux/gen12/codec/ddi/media_ddi_decode_av1_g12.cpp
AV1 film grain need it to decide Min/Max Chroma when apply noise.
> Pass matrix_coefficients of AV1 picture params

- media_driver/agnostic/common/codec/hal/codechal_encode_avc.cpp
- media_driver/agnostic/common/codec/hal/codechal_encode_hevc_base.cpp
test: command:
valgrind ffmpeg -hwaccel vaapi -hwaccel_output_fsormat vaapi -i test.264 -c:v hevc_vaapi -vframes 30 test.mp4 -y
valgrind ffmpeg -hwaccel vaapi -hwaccel_output_fsormat vaapi -i test.264 -c:v h264_vaapi -vframes 30 test.mp4 -y
you will see following errors like this:
=23516==    at 0xAAD6B3A: MhwVdboxMfxInterfaceG9<mhw_vdbox_mfx_g9_kbl>::GetRowstoreCachingAddrs(_MHW_VDBOX_ROWSTORE_PARAMS*) (mhw_vdbox_mfx_g9_X.h:251)
==23516==    by 0xA5FEDC2: CodechalHwInterface::SetRowstoreCachingOffsets(_MHW_VDBOX_ROWSTORE_PARAMS*) (codechal_hw.cpp:123)
==23516==    by 0xA78B296: CodechalEncodeHevcBase::SetSequenceStructs() (codechal_encode_hevc_base.cpp:853)
==23516==    by 0xA79FC31: CodechalEncHevcState::SetSequenceStructs() (codechal_encode_hevc.cpp:154)
==23516==    by 0xA9A39E9: …
> fix uninitialized value in hevc/avc encoder 

- media_driver/agnostic/gen11_jsl_ehl/vp/hal/vphal_renderer_g11_jsl_ehl.cpp
fix  #1049 driver build with -DENABLE_KERNELS=OFF is broken
Signed-off-by: Alex1 Zhang <alex1.zhang@intel.com>
> [VP] fix kernel build fail issue

- media_driver/linux/common/codec/ddi/media_ddi_decode_vp8.cpp
> Fix typo of golden/alt reference for vp8 decoding.

- media_driver/linux/common/codec/ddi/media_ddi_encode_avc.cpp
Correct the mapping of target useage for free driver. Fixed #768.
> [AVC VDEnc] Fix target usage mapping issue for free media driver

- media_driver/linux/common/ddi/media_libva_caps.cpp
Add libva check 1.10.0 for dynamic gpu session priority
Signed-off-by: Wang Dylan <dylan.wang@intel.com>
> [Media]Add libva check for dynamic gpu session priority

- media_driver/linux/common/ddi/media_libva_util.cpp
media_libva_util: Fix odd resolution handling of yuv420 formats
Ensure 2-byte width & height alignment for I420/YV12/IYUV surfaces
when there is no usage hint set for Encode or VPP write operations.
It seems the  odd resolution surface post-processing operation
(eg: nv12 to i420 conversion via vaGetImage API), causing a green
column on the right side of the video without this alignment.
Fixing #1037
> media_libva_util: Fix odd resoultion handling of yuv420 formats

- media_driver/linux/gen12/codec/ddi/media_ddi_decode_av1_g12.cpp
- media_driver/linux/gen12/ddi/media_libva_caps_g12.cpp
Driver only supports profile0 for AV1 decode on gen12, this change is to report correct profile
for av1 420 8bit and 420 10bit.
Signed-off-by: zefuli <zefu.li@intel.com>
> [Decode] Report the correct profile for AV1 decode

- media_driver/linux/common/ddi/media_libva.h
- media_driver/linux/common/ddi/media_libva_caps.cpp
- media_driver/linux/common/ddi/media_libva_caps.h
Fixing https://github.com/intel/media-driver/issues/1047
Signed of by: jay.yang@intel.com
> Fix loss of AYUV format in vaQuerySurfaceAttributes.

- media_driver/linux/common/codec/ddi/media_ddi_encode_base.cpp
While checking igd logs for encode failure debug, normal message was
printed and then VA_STATUS_ERROR_ENCODING_ERROR was returned, so it was
misleading. Critical failure before returning error will be good.
Signed-off-by: Sushma Venkatesh Reddy <sushma08reddy@gmail.com>
> Encode - Display assert message before returning error

- media_driver/linux/common/ddi/media_libva.cpp
vaExportSurfaceHandle works for packed RGB w/wo
VA_EXPORT_SURFACE_COMPOSED_LAYERS, it should work for packed YUV too
w/wo VA_EXPORT_SURFACE_COMPOSED_LAYERS
Example:
gst-launch-1.0 videotestsrc ! msdkvpp ! \
'video/x-raw(memory:DMABuf)',format=YUY2 ! glimagesink
> media_libva: export packed YUV when VA_EXPORT_SURFACE_COMPOSED_LAYERS is not set

- media_driver/linux/common/ddi/media_libva.cpp
Reverts intel/media-driver#1097, to correct the operation process. will re-merge after review and test later
> Revert "media_libva: export packed YUV when VA_EXPORT_SURFACE_COMPOSED_LAYERS is not set"

- media_driver/linux/common/os/mos_context_specific.cpp
These 2 functions are currently implemented within
a "#ifndef ANDROID" block in mos_context_specific.cpp.
When ANDROID is defined, these implementations are compiled out,
but they are still referenced by mos_os_specific.c, leading to
linking errors.
This patch simply moves the 2 functions outside of the
"#ifndef ANDROID" block so that they are always available.
This fixes https://github.com/intel/media-driver/issues/1100.
> Move the implementation of GetGpuPriority and SetGpuPriority

- media_driver/linux/common/ddi/media_libva.cpp
add mediaCopy ddi implementation.
linked libva PR: https://github.com/intel/libva/pull/243
add libva-utils PR: https://github.com/intel/libva-utils/pull/203
> add MediaCopy

- media_driver/linux/common/codec/ddi/media_libvpx_vp9.cpp
According VP9 spec section 7.2.2 color config semantics,
both subsampling_x and subsampling_y should be 0 for YUV444.
Only YUV440 subsampling_x=0 and subsampling_y=1.
fixes #1074
Signed-off-by: Lim Siew Hoon <siew.hoon.lim@intel.com>
> [Encode] Fixed VP9 444 frame header

- media_driver/linux/common/ddi/media_libva.cpp
when VA_EXPORT_SURFACE_COMPOSED_LAYERS is not set.
Example:
gst-launch-1.0 videotestsrc ! msdkvpp \
'video/x-raw(memory:DMABuf)',format=VUYA ! glimagesink
fixes #1114
Signed-off-by: Lim Siew Hoon <siew.hoon.lim@intel.com>
> media-libva: Add export AYUV color in vaExportSurfaceHandle

- media_driver/linux/common/codec/ddi/media_ddi_decode_base.cpp
For dynamic gpu session priority feature, due to add the log message in the
default branch, so separate the type from default branch.
Signed-off-by: Wang Dylan <dylan.wang@intel.com>
> [Decode] Separate VAContextParameterUpdateBufferType from default branch

- media_driver/linux/common/ddi/media_libva_putsurface_linux.cpp
currently media-driver doesn’t support Wayland/XWayland and Dri3. (Only for X and Dri2).
fixes #1095
> [Decode] Fix media driver crash by return error code instead of assert

- .github/workflows/ubuntu.yml
Cache needs to be up to date to avoid packages installation failures.
Change-Id: I5d6802978e3f3e5dbb0a414b4d6349d2ad8aac64
> ci: update cache before attempting to install packages

- .github/workflows/ubuntu.yml
Github images added clang-11 package, but somehow /usr/bin/clang-11
is missed. So, we better check that target is available rather than
package.
Change-Id: I377d9e709345f44ddcf37108c2f9db0e447cb761
> ci: fix detection of clang-11

- media_driver/linux/common/os/i915_production/mos_bufmgr.c
Fix av1 decode segment fault when calling function mos_gem_bo_process_reloc2
in media-driver/media_driver/linux/common/os/i915_production/mos_bufmgr.c
Signed-off-by: Zhang Yuankun <yuankunx.zhang@intel.com>
> Modify mos_gem_bo_clear_relocs in i915_production/mos_bufmgr.c

- media_driver/linux/gen11/ddi/media_sku_wa_g11.cpp
Enables the software workaround to disable calculation of the UV
offset by gmmlib. An incorrect UV offset was by returned  gmmlib
in vaDeriveImage which casues the shift in the color planes(UV).
This was observed during a chromecast session in mirror mode on ChromeOS
with H264 encode.
> vaDeriveImage: Enable WaDisableGmmLibOffsetInDeriveImage for JSL/EHL

- media_driver/linux/common/codec/ddi/media_ddi_decode_base.cpp
- media_driver/linux/common/codec/ddi/media_ddi_decode_vp8.cpp
- media_driver/linux/common/os/i915/include/mos_bufmgr.h
- media_driver/linux/common/os/i915/include/mos_bufmgr_priv.h
- media_driver/linux/common/os/i915/mos_bufmgr.c
- media_driver/linux/common/os/i915/mos_bufmgr_api.c
- media_driver/linux/common/os/i915_production/mos_bufmgr.c
- media_driver/linux/ult/libdrm_mock/mos_bufmgr_api_mock.c
- media_driver/linux/ult/libdrm_mock/mos_bufmgr_mock.c
We're attempting to remove PWRITE support from i915 for future platforms and this prepares the media driver for the move.
My attempt at media driver hacking looks correct to me but I've only compile-tested it.
> Stop using PWRITE

- media_driver/linux/gen11/ddi/media_sysinfo_g11.cpp
Workaround WaAlignYUVResourceToLCU is required on Gen11 and Gen12
systems. However, it was missed for EHL so, we were seeing difference in
surface size for JSL vs TGL. This patch ensures that there is no
difference in surface size between TGL and JSL.
Signed-off-by: Sushma Venkatesh Reddy <sushma.venkatesh.reddy@intel.com>
> Enable WaAlignYUVResourceToLCU to JSL systems

- media_driver/linux/common/ddi/media_libva_putsurface_linux.cpp
> Add area check in DdiMedia_PutSurface to avoid dst rectangle out of display region

- media_driver/agnostic/common/codec/hal/codechal_encode_mpeg2.cpp
new extension is added , 1080p@60, the level is highP,
the value is 2. so need to add a new check
Fixes #1201
> add new level definition for MPEG2 encode

- media_driver/linux/common/codec/ddi/media_ddi_encode_avc.cpp
> set the picture flag to be invalid frame if the ref frame is invalid

- media_driver/agnostic/common/cm/cm_device_rt_base.cpp
- media_driver/agnostic/common/os/mos_commandbuffer.h
- media_driver/agnostic/common/os/mos_graphicsresource.h
- media_driver/agnostic/common/os/mos_interface.h
- media_driver/agnostic/common/vp/hal/vphal_render_vebox_denoise.cpp
- media_driver/agnostic/common/vp/hal/vphal_render_vebox_denoise.h
- media_driver/agnostic/gen12/hw/mhw_state_heap_hwcmd_g12_X.h
- media_driver/linux/common/os/mos_graphicsresource_specific.h
- media_driver/linux/common/os/mos_interface.cpp
- media_driver/linux/common/os/mos_os_specific.c
- media_driver/media_driver_next/agnostic/gen12/codec/hal/dec/av1/features/decode_av1_filmgrain_feature_g12.cpp
- media_driver/media_driver_next/agnostic/gen12/codec/hal/dec/av1/packet/decode_av1_packet_g12.cpp
- media_softlet/agnostic/common/codec/hal/dec/av1/features/decode_av1_basic_feature.cpp
- media_softlet/agnostic/common/codec/hal/dec/av1/packet/decode_av1_picture_packet.cpp
- media_softlet/agnostic/common/codec/hal/dec/shared/bufferMgr/decode_allocator.cpp
- media_softlet/agnostic/common/codec/hal/dec/shared/bufferMgr/decode_allocator.h
- media_softlet/agnostic/common/codec/hal/dec/shared/bufferMgr/decode_resource_auto_lock.h
- media_softlet/agnostic/common/codec/hal/dec/shared/statusreport/decode_status_report.cpp
- media_softlet/agnostic/common/os/mos_commandbuffer_next.h
- media_softlet/agnostic/common/os/mos_graphicsresource_next.h
- media_softlet/agnostic/common/os/mos_utilities_next.h
- media_softlet/agnostic/common/shared/bufferMgr/media_allocator.cpp
- media_softlet/agnostic/common/shared/bufferMgr/media_allocator.h
- media_softlet/agnostic/common/vp/hal/bufferMgr/vp_allocator.cpp
- media_softlet/agnostic/common/vp/hal/bufferMgr/vp_allocator.h
- media_softlet/linux/common/os/mos_graphicsresource_specific_next.h
Fix typos in function name/comments (resouces->resources).
Fixes: #1010
> Fix typo issue (resouces->resources)

- media_driver/agnostic/common/vp/hal/vphal_render_vebox_base.cpp
Enable PROCAMP when 2pass CSC is also enabled.
Fixes: #1138
Signed off by: jay.yang@intel.com
> [VP] Fix 2pass CSC PROCAMP not work issue

- media_driver/linux/gen12/ddi/media_libva_caps_g12.cpp
Provide mem_types VA_SURFACE_ATTRIB_MEM_TYPE_VA and VA_SURFACE_ATTRIB_MEM_TYPE_DRM_PRIME_2
for decode and encode when querying surface attributes on Gen12.
Signed-off-by: Yuankun Zhang <yuankunx.zhang@intel.com>
> [Decode][Gen12] Provide mem_types when querying surface attributes

- cmrtlib/linux/CMakeLists.txt
Respect `MEDIA_BUILD_FATAL_WARNINGS` to avoid the following build failure when the user provides `_FORTIFY_SOURCE`:
```
In file included from /home/buildroot/autobuild/instance-0/output-1/host/x86_64-buildroot-linux-gnu/sysroot/usr/include/dlfcn.h:22,
from /home/buildroot/autobuild/instance-0/output-1/build/intel-mediadriver-19.4.0r/cmrtlib/linux/../linux/share/cm_include.h:30,
from /home/buildroot/autobuild/instance-0/output-1/build/intel-mediadriver-19.4.0r/cmrtlib/agnostic/share/cm_printf_host.cpp:23:
/home/buildroot/autobuild/instance-0/output-1/host/x86_64-buildroot-linux-gnu/sysroot/usr/include/features.h:397:4: error: #warning _FORTIFY_SOURCE requires compiling with optimization (-O) [-Werror=cpp]
397 | #  warning _FORTIFY_SOURCE requires compiling with optimization (-O)
| …
```
> cmrtlib/linux/CMakelists.txt: respect MEDIA_BUILD_FATAL_WARNINGS

- media_softlet/linux/common/ddi/media_libva_interface_next.cpp
media_libva_putsurface_linux.h is already included in
https://github.com/intel/media-driver/blob/master/media_softlet/linux/common/ddi/media_libva_interface_next.cpp#L29
which is guarded by defined(X11_FOUND).
Removing this superflous line fixed non-X11 builds:
In file included from intel-mediadriver-6c183bf8d5c002549a486e4730bbafec04fc1fc8/media_softlet/linux/common/ddi/media_libva_interface_next.cpp:38:0:
intel-mediadriver-6c183bf8d5c002549a486e4730bbafec04fc1fc8/media_driver/linux/common/ddi/media_libva_putsurface_linux.h:31:29: fatal error: va/va_dricommon.h: No such file or directory
#include <va/va_dricommon.h>
because va/va_dricommon.h is only present when libva was built with X11
support:
https://github.com/intel/libva/blob/master/va/x11/Makefile.am#L41
> [Media Common] Fix non-X11 build

- media_driver/linux/common/ddi/media_libva.cpp
- media_driver/linux/common/ddi/media_libva.h
- media_driver/linux/common/ddi/media_libva_caps.cpp
- media_driver/linux/common/ddi/media_libva_caps.h
- media_driver/linux/common/ddi/media_libva_interface.cpp
- media_driver/linux/gen12/ddi/media_libva_caps_g12.cpp
- media_driver/linux/gen12/ddi/media_libva_caps_g12.h
- media_softlet/linux/common/ddi/media_libva_interface_next.cpp
https://github.com/intel/libva/pull/513
> Display caps for vaCopy

- media_driver/linux/common/ddi/media_libva.h
- media_driver/linux/common/ddi/media_libva_caps.cpp
- media_driver/linux/common/ddi/media_libva_caps.h
Fix loss of Y210 and Y410 format in vaQuerySurfaceAttributes.
Signed-off-by: Yuankun Zhang <yuankunx.zhang@intel.com>
> [VP] Fix loss of Y210 and Y410 format in vaQuerySurfaceAttributes.

- media_driver/linux/common/ddi/media_libva_caps.cpp
Fix regression:libva conformance failures since #1229
Signed-off-by: Zhang Yuankun <yuankunx.zhang@intel.com>
> [VP] Fix regression which caused by #1229

- media_softlet/agnostic/common/codec/hal/dec/av1/features/decode_av1_tile_coding.cpp
The tile descriptors are allocated with malloc. Fixes #1274.
```
Mismatched free() / delete / delete []
at 0x484584F: operator delete(void*) (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
by 0x160322FD: decode::Av1DecodeTile::~Av1DecodeTile() (decode_av1_tile_coding.cpp:40)
by 0x16029F39: decode::Av1BasicFeature::~Av1BasicFeature() (decode_av1_basic_feature.cpp:34)
by 0x16029F77: decode::Av1BasicFeature::~Av1BasicFeature() (decode_av1_basic_feature.cpp:57)
by 0x15F29EAB: MediaFeatureManager::Destroy() (media_feature_manager.cpp:117)
by 0x15E54551: MediaFeatureManager::~MediaFeatureManager() (media_feature_manager.h:159)
by 0x15E83775: decode::DecodeFeatureManager::~DecodeFeatureManager() (decode_feature_manager.h:61)
by 0x15E837D1: …
```
> [Decode] AV1 Fix mismatched free

- media_driver/linux/common/codec/ddi/media_ddi_decode_mpeg2.cpp
reference frame is invalid
fixes #1119
> [Decode] avoid the array out of bounds when the forward or backward reference frame is invalid

- media_driver/linux/common/codec/ddi/media_ddi_decode_mpeg2.cpp
reference frame is invalid
fixes #1119
> [Decode] avoid the array out of bounds when the forward or backward

- media_driver/linux/common/ddi/media_libva_util.cpp
This is based on commit 55268ab458e20365f61d3c636e5eb2597e2d3a30 [1].
It extends the logic to external surfaces.
[1] https://github.com/intel/media-driver/commit/55268ab458e20365f61d3c636e5eb2597e2d3a30
> Handle odd dimensions for external surfaces

- media_driver/agnostic/gen12/cm/cm_hal_g12.h
This commit address the following compilation error when building with
cmake -DGEN8=OFF. Partially fixes #1065.
media-driver/media_driver/agnostic/gen12/cm/cm_hal_g12.h:32:10:
fatal error: mhw_render_hwcmd_g8_X.h: No such file or directory
> [Media Common] Fix include when building with -DGEN8=OFF

- media_driver/linux/common/ddi/media_libva_caps.cpp
- media_driver/linux/gen11/ddi/media_libva_caps_g11.cpp
Add MemoryType attribute VA_SURFACE_ATTRIB_MEM_TYPE_DRM_PRIME_2 support for Gen9-Gen11
Fixed #1241
Signed-off-by: Effie Yu effie.yu@intel.com
> [Media Common] Add Attribute to QuerySurfaceAttributes

- media_softlet/linux/common/os/mos_utilities_specific_next.cpp
- media_softlet/linux/common/os/mos_utilities_specific_next.h
This commit fix the #1300
Signed-off-by: Wang, Pingli <pingli.wang@intel.com>
> [Media Common]Fix the user setting memory free

- media_driver/linux/gen12/ddi/media_libva_caps_g12.cpp
Fill in VAConfigAttribValEncHEVCFeatures and VAConfigAttribValEncHEVCBlockSizes
with the approriate values for HEVC VDENC.
Fixes #1190.
> [Encode] Report sub features for HEVC

- media_driver/linux/gen9/ddi/media_sku_wa_g9.cpp
- media_driver/media_interface/media_interfaces_m9_glk/media_interfaces_g9_glk.cpp
- media_driver/media_interface/media_interfaces_m9_glk/media_interfaces_g9_glk.h
Enable VP8 encode for Gemini Lake. Interface code was inherited from
KBL paths. Resolves #1313.
> [Encode] GLK enable VP8

- media_driver/linux/common/ddi/media_libva.cpp
Without this, querying capabilities (e.g. with vadumpcaps) will find as many uninitialised format entries as it asks for.
Before:
```
$ vadumpcaps --subpicture-formats
{
"build_version": {
"major": 1,
"minor": 14,
"micro": 0,
},
"driver_version": {
"major": 1,
"minor": 14,
},
"driver_vendor": "Intel iHD driver for Intel(R) Gen Graphics - 22.2.0 (4485349d8)",
"subpicture_formats": [
{
"pixel_format": "",
"byte_order": "unknown",
"bits_per_pixel": 0,
"flags": [
],
},
{
"pixel_format": "",
"byte_order": "unknown",
"bits_per_pixel": 0,
"flags": [
],
},
{
"pixel_format": "",
"byte_order": "unknown",
"bits_per_pixel": 0,
"flags": [
],
},
{
"pixel_format": "",
"byte_order": "unknown",
"bits_per_pixel": 0,
"flags": [
],
},
],
},
```
After:
```
$ ./vadumpcaps --subpicture-formats
{ …
```
> Return zero subpicture formats

- media_driver/linux/gen11/ddi/media_libva_caps_g11.cpp
- media_driver/linux/gen11/ddi/media_libva_caps_g11.h
Like gen12, gen11 also has feature support which doesn't match the
original gen9 implementation, so we need to expose these attributes
there as well.
I do think all encoders should probably expose these attributes so that the user doesn't need to carry default settings based on the gen9 i965 implementation.  I'm not sure exactly what the capabilities of gen9 are, though, so I've only done gen11 here.
> Report HEVC features and block sizes for gen11

- media_driver/agnostic/common/codec/hal/codechal_decode_vc1.cpp
This will silence the warning -Wbitwise-instead-of-logical for newer version of clang.
fixes intel#1338
> Change | to || for booleans

- docs/media_features.md
Composition path does not support conversion from BT2020 RGB to BT2020
YUV, BT2020->BT601/BT709, BT601/BT709 -> BT2020.
https://github.com/intel/media-driver/blob/16ca483d3c7ae5fed2c4a2339f615d2a0887adfd/media_driver/agnostic/common/vp/hal/vphal_render_composite.cpp#L6523
Related issues: https://github.com/intel/media-driver/issues/1280 and https://github.com/intel/media-driver/issues/1225
Signed off by: jay.yang@intel.com
> [VP] Doc update: Composition path does not support BT2020 color space

- media_driver/media_top_cmake.cmake
Otherwise a wrong version of igdgmm might be used to build the media
driver
Change-Id: I8f3074047ec45bb4721524861ffaa695eca8d9b6
> Add check for igdgmm version

- media_driver/cmake/linux/media_gen_flags_linux.cmake
Added missing cmake option GEN12_ADLN for ADL-N SoCs
> ADL-N Support : Added the cmake options GEN12_ADLN 

- media_softlet/agnostic/common/codec/hal/enc/hevc/features/encode_hevc_vdenc_const_settings.h
- media_softlet/agnostic/common/codec/hal/enc/shared/features/encode_tile.h
Fixes these errors:
media_softlet/agnostic/common/codec/hal/enc/shared/features/encode_tile.h:506:125: error: array must be initialized with a brace-enclosed initializer
PMHW_BATCH_BUFFER m_tileLevelBatchBuffer[m_codecHalNumTileLevelBatchBuffers][EncodeBasicFeature::m_vdencBrcPassNum] = {0};  //!< Tile level batch buffer for each tile
media_softlet/agnostic/common/codec/hal/enc/hevc/features/encode_hevc_vdenc_const_settings.h:118:55: error: array must be initialized with a brace-enclosed initializer
m_rowOffsetsForBoost = {0, 3, 5, 2, 7, 4, 1, 6};
> fix build error with gcc-4.9

- cmrtlib/linux/hardware/drm_device.h
When a device is not bound to a driver, the `driver` link does not
exist, so we can stop parsing the `sysfs` files, as that device is not
useful, and return.
Fixes #1383,
> [CM] Skip parsing info when device is unbound

- media_driver/linux/Xe_M/ddi/media_libva_caps_dg2.cpp
- media_driver/linux/gen12/ddi/media_libva_caps_g12.cpp
- media_driver/linux/gen12/ddi/media_libva_caps_g12.h
1. Correct the capability report for SCC prediction direction on Gen12, SCC only support I/P/Low Delay B on Gen12.
2. Fixes #1401
> Correct capability report for Gen12 SCC prediction direction

- media_driver/linux/gen12/ddi/media_libva_caps_g12.cpp
1. BRC is not supported in SCC on Gen12, remove BRC for SCC profiles
2. Fixes #1400
> Correct Gen12 capability reporting for SCC bitrate control mode

- media_driver/linux/Xe_M/ddi/media_sku_wa_xe.cpp
- media_driver/linux/common/vp/ddi/media_libva_vp.c
- media_driver/linux/gen11/ddi/media_sku_wa_g11.cpp
- media_driver/linux/gen12/ddi/media_sku_wa_g12.cpp
HDR10 Tone Mapping (HDR to HDR, HDR to SDR, HDR to EDR as of now) will be supported on the below platforms.
1. KBL GT2/GT3/GT4;
2. GLK (this is a specific requests, perf can not be guarantee due to limited EUs);
3. ICL;
4. TGL/ADL/DG1;
5. DG2;
Signed-off-by: Furong Zhang <furong.zhang@intel.com>
> Added HDR10 Tone Mapping capability report.

- media_driver/agnostic/gen12/codec/hal/codechal_vdenc_vp9_g12.cpp
Previously, the calculation of maxTileNumber is wrong on Gen12 VP9, this will cause crash when input 4x4 tiles. Fixes #1314
> Correct the calculation method of maxTileNumber for Gen12 VP9

- media_driver/linux/common/codec/ddi/media_ddi_decode_vc1.cpp
Enable intensity compensation to avoid the artifact for B frame decoding
Fixes #752
> [Decode] enable intensity compensation for vc1 decoding

- media_driver/agnostic/common/vp/hal/vphal_renderer.cpp
Fix: https://github.com/intel/media-driver/issues/1394
> Fix driver crash with no kernel binary

- media_driver/agnostic/common/codec/hal/codechal_encode_hevc.cpp
When HierarchicalFlag > 0 for I frame LDB, will ignore the vaule of HierarchLevelPlus1. For compatibility purpose, we keep m_hevcPicParams->HierarchLevelPlus1 == 0 here. Fixes #1395
> Avoid incorrect error reporting for LDB when HierarchicalFlag > 0

- docs/media_features.md
HVEC/VP9 12bit use P016/Y216/Y416 with least significant 4 bits are set
to zero
> [Decode] Update the readme for hevc/ vp9 12bit output

- media_driver/linux/common/ddi/media_libva.h
- media_driver/linux/common/ddi/media_libva_caps.cpp
- media_driver/linux/common/ddi/media_libva_caps.h
- media_driver/linux/gen11/ddi/media_libva_caps_g11.cpp
- media_driver/linux/gen12/ddi/media_libva_caps_g12.cpp
XYUV is used in 4:4:4 8bit content decoding and encoding on Linux, so we need to support this format in vp too
> add support for xyuv in vp 

- media_driver/agnostic/Xe_M/Xe_XPM/codec/media_srcs.cmake
Fix the issue of missing contitional checking for None-Free kernel build in cmake file. Fixes #1517.
> [Decode] Add missing conditional check for None-Free Kernel build

- media_driver/agnostic/common/vp/media_srcs.cmake
- media_softlet/agnostic/common/media_interfaces/media_srcs.cmake
Fixed #1520
Remove redundant contents in cmake file, because these old source folders have been removed after refactor.
Signed-off-by: Gu, Lihao lihao.gu@intel.com
> Fix cmake warnings

- media_driver/linux/gen12/ddi/media_sysinfo_g12.cpp
Fixes media driver compatibility with the i9-12950HX mobile processor.
Based off of this mesa commit: https://gitlab.freedesktop.org/mesa/mesa/-/commit/df5b14969f9869f363bcc8b2a564c85aaa481597
More info: https://bugs.launchpad.net/ubuntu/+source/mesa/+bug/1955566/comments/0
> Add Alder Lake S PCI ID for the i9-12950HX mobile processor

- media_softlet/linux/common/vp/ddi/ddi_vp_functions.cpp
[Media Common] [VP] dont include va_dricommon.h on non X11 builds
<va/va_dricommon.h> is unavailable and not in non-X11 libva 2.16.0
- Fixes #1549 
tested with GBM build. 
Signed-off-by: Rudi Heitbaum <rudi@heitbaum.com>
> [Media Common] [VP] Remove unused include fixes #1549

- cmrtlib/linux/hardware/drm_device.h
This fixes issue #1507 
readlink() will not place a terminating 0, which means that we cannot use unintialized memory as a destination.
NOTE: it is not sufficient to write a null-string to the buffer, because that only sets the first character to 0. Every byte in the destination string should be 0, so that when readlink() has written content, it is always null-terminated.
> Fix reads from uninitialized memory.

- media_driver/linux/common/ddi/media_libva.cpp
- media_softlet/linux/common/ddi/media_libva_interface_next.cpp
Fix #1537
On discrete cards which have local memory, map shadow buffer instead of surface bo. Otherwise cpu memcpy will be very slow.
> [Media Common] vaGetImage optimization on D-card.

- media_driver/linux/common/ddi/media_libva.cpp
> device handle range fix

- media_driver/linux/gen10/ddi/media_sku_wa_g10.cpp
- media_driver/linux/gen8/ddi/media_sku_wa_g8.cpp
- media_driver/linux/gen9/ddi/media_sku_wa_g9.cpp
Fix: https://github.com/intel/media-driver/issues/1590
Add sw swizzling sku for Gen8/9/10, without which there will be perf
drop because mos_gem_bo_map_unsynchronized is called.
> [Media Common] SW swizzling regression fix for Gen8/9/10

- media_driver/agnostic/Xe_M/Xe_HPM/codec/hal/media_srcs.cmake
- media_driver/agnostic/Xe_M/Xe_XPM/codec/hal/media_srcs.cmake
- media_driver/agnostic/common/codec/hal/codechal_encoder_base.cpp
- media_driver/agnostic/common/codec/hal/codechal_huc_cmd_initializer.h
- media_driver/agnostic/gen11/codec/hal/codechal_huc_cmd_initializer_g11.h
This commit fix the compilation error when setting HEVC_Encode_Supported="no"
Fix for https://github.com/intel/media-driver/issues/1540
> [Encode] Fix build issue when setting HEVC_Encode_Supported="no"

- media_driver/media_softlet/agnostic/Xe_R/Xe_HP_Base/renderhal/renderhal_xe_hp_base.cpp
- media_softlet/agnostic/common/codec/hal/codechal_debug.cpp
- media_softlet/agnostic/common/os/mos_utilities_next.cpp
Both clang and gcc fail creating debug builds.
This fix addresses the following compile warnings/errors:
```
comparison of constant 8 with expression of type 'MHW_ROTATION' (aka '_MHW_ROTATION') is always true
```
```
pointer ‘oldPtr’ may be used after ‘void* realloc(void*, size_t)’
```
```
the address of ‘MOS_SURFACE::OsResource’ will never be NULL
```
This fixes issue #1490
> Fix debug builds

- media_driver/agnostic/media_srcs.cmake
- media_driver/cmake/linux/media_gen_flags_linux.cmake
- media_driver/linux/media_srcs.cmake
- media_driver/media_interface/media_srcs.cmake
Allowing the driver code to be disabled for Gen10 reduces the binary size by an additional 6.6 MiB over the 4 MiB reduction when removing the media kernels alone.
````
text     data   bss       dec      hex  filename
45485460  2374412 38736  47898608  2dadff0  iHD_drv_video.so # -DGEN10=ON
41422146  2237132 38768  43698046  29ac77e  iHD_drv_video.so # -DGEN10=OFF before this patch
34483374  2219940 38704  36742018  230a382  iHD_drv_video.so # -DGEN10=OFF after this patch
````
This change was enabled by the compile fix in commit e47460dc0363 ("Encode] Fix build issue when setting -DGEN10=OFF").
Closes: https://github.com/intel/media-driver/issues/1065
> Disable Gen10 driver code when -DGEN10=OFF

- media_driver/agnostic/media_srcs.cmake
- media_driver/cmake/linux/media_gen_flags_linux.cmake
- media_driver/linux/media_srcs.cmake
- media_driver/media_interface/media_interfaces_m8_bdw/media_interfaces_g8_bdw.h
- media_driver/media_interface/media_srcs.cmake
Disable Gen9 driver code when -DGEN9=OFF
Allowing the driver code to be disabled for Gen9 reduces the
binary size by an additional 2.1 MiB over the 5.0 MiB reduction when
removing the media kernels alone.
````
text     data   bss       dec      hex  filename
41573236  2237132 38768  43849136  29d15b0  iHD_drv_video.so # -DGEN9=ON
36324898  2237132 38768  38600798  24d005e  iHD_drv_video.so # -DGEN9=OFF before this patch
34124420  2196548 38384  36359352  22accb8  iHD_drv_video.so # -DGEN9=OFF after this patch
````
>  Disable Gen9 driver code when -DGEN9=OFF

- media_driver/agnostic/media_srcs.cmake
- media_driver/cmake/linux/media_gen_flags_linux.cmake
- media_driver/linux/common/cm/hal/cm_command_buffer_os.cpp
- media_driver/linux/media_srcs.cmake
- media_driver/media_interface/media_srcs.cmake
Disable Gen11 driver code when -DGEN11=OFF
Allowing the driver code to be disabled for Gen11 reduces the
binary size by an additional 1.0 MiB over the 3.8 MiB reduction when
removing the media kernels alone.
````
text     data   bss       dec      hex  filename
41573236  2237132 38768  43849136  29d15b0  iHD_drv_video.so # -DGEN11=ON
38439404  1417324 38832  39895560  260c208  iHD_drv_video.so # -DGEN11=OFF before this patch
37402536  1387428 38672  38828636  2507a5c  iHD_drv_video.so # -DGEN11=OFF after this patch
````
> Disable Gen11 driver code when -DGEN11=OFF

- media_softlet/linux/common/media_srcs.cmake
I believe this was missed in commit df7b0bd796ae ("[Encode] move codechal setting create from hal to ddi")
> Remove stale cmake subdirectory

- media_driver/linux/Xe_M/ddi/media_libva_caps_dg2.cpp
Tested with FFmpeg `hevc_{qsv,vaapi} -global_quality 25` on DG2/A380.
Also the AV1 ICQ need extra handling since it is not implemented yet.
> [Encode] Fix the HEVC ICQ capability on DG2

- media_driver/linux/Xe_M/ddi/media_sku_wa_xe.cpp
Fixes: intel/media-driver#1628
Sku table did not init on Linux, it need do 8x alignment.
> [VP] Fix tonemap vaapi extremely slow on certain input size issue

- media_driver/agnostic/gen12/codec/hal/codechal_vdenc_vp9_g12.cpp
- media_driver/agnostic/gen12/codec/hal/codechal_vdenc_vp9_g12.h
Recon surface does not need fill padding. Remove this CPU padding to improve power and performance.
> [VP9][Encode] Do not fill padding to recon surface

- media_softlet/linux/common/ddi/media_libva_util_next.cpp
This is based on commit 25a68cb146b6e5310c6b5e1bd202d5e9690635a9 [1]. 
It extends the logic for external non-compressible surfaces on MTL.
[1] https://github.com/intel/media-driver/commit/25a68cb146b6e5310c6b5e1bd202d5e9690635a9
> Handle odd dimensions for external non-compressible surfaces on MTL

- media_driver/linux/gen10/ddi/media_sku_wa_g10.cpp
- media_driver/linux/gen8/ddi/media_sku_wa_g8.cpp
- media_driver/linux/gen9/ddi/media_sku_wa_g9.cpp
> Add WaDisableGmmLibOffsetInDeriveImage WA on gen8/9/10 to fix chromeOS UV shift

- media_driver/agnostic/gen12/vp/hal/vphal_render_vebox_g12_base.cpp
- media_driver/linux/gen12/ddi/media_sku_wa_g12.cpp
Fixes: https://github.com/intel/media-driver/issues/1672
Sku table did not init on Linux ADL-S and RPL-S, and it didn't update 3dlutenable params, it need do 8x alignment.
> Fix tonemap vaapi on certain input size issue

- media_driver/agnostic/gen12/codec/hal/codechal_vdenc_vp9_g12.cpp
- media_softlet/agnostic/common/os/mos_utilities.h
- media_softlet/agnostic/common/os/mos_utilities_next.cpp
- media_softlet/linux/common/os/mos_interface.cpp
Direct fill padding to tiled format buffer to avoid unnecessary memory copies between tiled buffer and linear buffer.
> [VP9] [Encode] Fill padding to tiled format buffer directly

- media_driver/linux/gen9/ddi/media_sku_wa_g9.cpp
> Remove WaDisableGmmLibOffsetInDeriveImage WA for APL/GLK to fix chromeOS UV shift

- .github/workflows/ubuntu.yml
- README.md
> .github: Drop libegl1-mesa-dev and libgl1-mesa-dev

- media_softlet/agnostic/common/shared/statusreport/media_status_report.cpp
- media_softlet/agnostic/common/shared/statusreport/media_status_report.h
Regarding app may query status report in async mode, global resource protection is needed.
> [Decode] Add mutex to protect global resource in status report

- media_driver/linux/common/ddi/media_libva.cpp
The output formats from the JPEG decoder are currently not included
in the DRM format mapping functions. This means that any attempt to
call vaExportSurface on JPEG images will fail.
However, there is no functional gap beyond the missing mappings, so if
we add them in, exporting will then work correctly.
The four formats in question are IMC3, 422H, 422V, and 444P.
* 422H and 444P have trivial 1:1 mappings.
* IMC3 can be treated the same as I420, because the only difference is
the chroma pitch, and that's explicitly set in the descriptor
* 422V (aka 440P) has the same memory layout as 422H - it's just a
difference in how the consumer handle the chroma
I also added the missing XYUV composite object mapping - it was already
present for separate planes.
Tested with ffmpeg+mpv.
> [Media Common] Add DRM format mappings for JPEG decoder output

- media_softlet/linux/common/ddi/media_libva_interface_next.cpp
This is the softlet equivalent of my previous change to add DRM format mappings for the JPEG decoder output formats to the legacy code path.
Tested compilation, but don't have the hardware to test at runtime.
> [Media Common] Add DRM format mappings for JPEG output to softlet

- media_softlet/agnostic/common/codec/hal/enc/vp9/packet/encode_vp9_vdenc_packet.cpp
- media_softlet/linux/Xe_M_plus/ddi/media_sku_wa_mtl.cpp
Fill the padding for unaligned height input with gmmlib CpuBlt() for VP9 encoding on MTL.
> [VP9] [Encode] Fill padding with gmm CpuBlt on MTL

- media_softlet/linux/common/codec/ddi/enc/ddi_encode_avc_specific.h
- media_softlet/linux/common/codec/ddi/enc/ddi_encode_hevc_specific.h
This is to fix msdkh264enc/msdkh265enc incorrect encoded output when having BGRx input.
> [Encode] XRGB force to do swizzle for AVC/HEVC

- media_softlet/agnostic/common/codec/hal/dec/hevc/features/decode_hevc_basic_feature.cpp
- media_softlet/agnostic/common/codec/hal/dec/hevc/features/decode_hevc_reference_frames.cpp
Media driver should avoid stopping playback by giving an ambiguous error since invalid reference will not cause gpu hang.
But application should take care of the assert message indicating to error syntax which may cause output corruption.
> [Decode] Optimize error syntax check for hevc

- media_softlet/linux/common/os/i915/mos_bufmgr.c
Query the drm device firstly and init specific drm implement dynamically
Note: this is still need to add build option '-DENABLE_NEW_KMD=ON' to enable xe drm.
> [Decode] Add xe drm init entry

- .github/workflows/ubuntu.yml
- media_driver/cmake/linux/media_gen_flags_linux.cmake
Cc: @XinfengZhang, @Sherry-Lin
I expect the MTL-disabled build to fail with:
```
In file included from /root/projects/intel/media-driver/media_softlet/media_interface/media_interfaces_arl/media_interfaces_arl.cpp:30:    
/root/projects/intel/media-driver/media_softlet/media_interface/media_interfaces_arl/media_interfaces_arl.h:32:10: fatal error: 'media_interfaces_mtl.h' file not found    
#include "media_interfaces_mtl.h"    
¦^~~~~~~~~~~~~~~~~~~~~~~~    
1 error generated.    
```
> Add CI builds that disable MTL and ARL support

- media_driver/linux/common/codec/ddi/media_libva_decoder.cpp
It is possible a BO in the completed report list has been destroyed from user app.
> media_libva_decoder: don't return early

- media_driver/agnostic/gen12/codec/hal/codechal_encode_csc_ds_g12.cpp
- media_driver/linux/common/codec/ddi/media_ddi_encode_avc.h
- media_driver/linux/common/codec/ddi/media_ddi_encode_hevc.h
The patch is to fix BGRx AVC/HEVC enc on ADL with gstVPL. 
reproducer cmd: 
1. gst-launch-1.0 ximagesrc -v use-damage=0 num-buffers=120 startx=0 starty=0 endx=800 endy=600 ! video/x-raw,framerate=30/1 ! msdkh265enc rate-control=cqp ! video/x-h265,profile=screen-extended-main ! filesink location=yocto-ximagesrc-adl.h265
2. gst-launch-1.0 ximagesrc -v use-damage=0 num-buffers=120 startx=0 starty=0 endx=800 endy=600 ! video/x-raw,framerate=30/1 ! msdkh264enc rate-control=cqp ! video/x-h264,profile=baseline ! filesink location=yocto-ximagesrc-adl.h264
3.	gst-launch-1.0 filesrc location=BGRX_1080.yuv ! videoparse width=1920 height=1080 format=bgrx ! msdkh264enc ! filesink location=test.h264
4.	gst-launch-1.0 filesrc location=BGRX_1080.yuv ! videoparse width=1920 height=1080 format=bgrx ! …
> [Encode] Fix BGRx AVC/HEVC Enc for g12

- media_driver/linux/common/media_interfaces/media_interfaces.cpp
- media_driver/media_interface/media_interfaces_dg2/media_interfaces_dg2.cpp
> Fix double free crash when create mmd fail

- media_driver/linux/gen12/ddi/media_libva_caps_g12.cpp
Max resolution of MPEG2 is 2K.
assigning 2048x2048 for MPEG2 attributies
fixes: #1830
> Add max resolution for MPEG2 on Gen12

- media_driver/agnostic/gen9/codec/hal/codechal_encode_hevc_g9.cpp
fix PCODECHAL_ENC_HEVC_B_MB_ENC_CURBE_G9 build issue
> [HEVCe] fix a build issue

- media_softlet/linux/common/os/xe/mos_bufmgr_xe.c
recommend flagging all potential scanout surfaces as SCANOUT
> [Media Common] Set Scanout by default

- README.md
Fixes: #1852, #1832
Av1 decode needs filmgrain kernel support, and free kernel build will not support av1 decode.
> [Decode] Remove av1 decode from feature list on some platforms

- media_softlet/linux/common/ddi/media_libva_interface_next.cpp
This applies the same fix in commit 722793d2eb507755affcacb151189e1bd052ce4c to media_libva_interface_next.cpp.
Should close #1859.
Tested locally under mpv and seems to work.
> [VP] Port segfault fix from media_libva to media_libva_next

- media_softlet/linux/xe2_hpm_r0/encode/hevc/ddi/capstable_data_hevc_encode_xe2_hpm_r0_specific.h
The patch is to add Y210 HEVC encode support  on BMG with gstreamer-va.
Tested with below:
`gst-launch-1.0 -v filesrc location=Elecard2_1920x1080_4mbps_60fps_Main_at_L4.1_10bit_422.mkv ! matroskademux ! h265parse ! vah265dec ! "video/x-raw, format=Y210" ! vah265enc bitrate=3000 rate-control=cbr ! filesink location = output_Elecard2_1920x1080_4mbps_60fps_Main_at_L4.1_10bit_422_cbr_system_memory.h265`
`gst-launch-1.0 -v filesrc location=Elecard2_1920x1080_4mbps_60fps_Main_at_L4.1_10bit_422.mkv ! matroskademux ! h265parse ! vah265dec ! "video/x-raw(memory:VAMemory), format=Y210" ! vah265enc bitrate=3000 rate-control=cbr ! filesink location = output_Elecard2_1920x1080_4mbps_60fps_Main_at_L4.1_10bit_422_cbr_va_memory.h265`
`gst-launch-1.0 -v filesrc …
> [Encode] Add Y210 caps for BMG HEVC encode

- README.md
The link to Ubuntu is not valid now so update to a new one.
> [Readme] Update Ubuntu link

- media_driver/linux/Xe_M/ddi/media_sku_wa_xe.cpp
- media_driver/linux/gen12/ddi/media_sku_wa_g12.cpp
> Av1 decode needs filmgrain kernel support, and free kernel build will not support av1 decode.
This [has been fixed in the docs](https://github.com/intel/media-driver/pull/1853) and needs to be fixed in libva's capabilities as well.
Fixes:
https://github.com/intel/media-driver/pull/1853#issuecomment-2385982039
Downstream https://github.com/mpv-player/mpv/issues/14941
Downstream https://trac.ffmpeg.org/ticket/11213
> [Decode] Do not report AV1d support in free kernel build on TGLx and DG2

- media_softlet/linux/common/ddi/capstable_data_image_format_definition.h
This is to port https://github.com/intel/media-driver/commit/8c7b05bf8a81961c1f111b75cae99818a8bd8aa9 to BMG
> [VP] Change RGB mask and order for BMG

- media_driver/linux/Xe_M/ddi/media_sku_wa_xe.cpp
disable DG2 Height alignment WA
> [Encode] Fix ACM multi-channel AVC encode performance degradation

- media_driver/linux/gen12/ddi/media_sku_wa_g12.cpp
This Wa is needed for using DG1 with the upstream i915 kernel.
Partially fixes:
https://github.com/intel/media-driver/issues/1415#issuecomment-2042018933
The other part needs to be fixed on KMD side by disabling `HCP_POWERGATE` and `MFXVDENC_POWERGATE` for DG1. Unlike TGLx, DG1 doesn't support sub-pipe PG and setting these bits will cause HEVC and VP9 decoding failure.
See also https://gitlab.freedesktop.org/drm/i915/kernel/-/issues/13381
> [Media Common] Enable Wa to disable object capture for DG1
