intel/media-driver

media_driver/linux/common/os/mos_context_specific.cpp
media_driver/linux/common/os/mos_context_specific.h

Fix mos build issue

---

README.md

update supported codecs table for BXT and APL platforms

Update supported codecs for BXT and APL platforms

---

media_driver/linux/common/ddi/media_libva_caps.cpp

export more decode surface attributes

---

media_driver/linux/ult/ult_app/driver_loader.cpp

UT: fix the log message format in unit test.

---

media_driver/linux/common/codec/ddi/media_ddi_encode_hevc.cpp

limit the reference list in the [0 num_ref_idx_l0_active_minus1/num_ref_idx_l1_active_minus1]

[HEVC enc]add check for the reference list in the slice header

---

media_driver/linux/common/ddi/media_libva_caps.cpp
media_driver/linux/common/ddi/media_libva_caps.h

set default RC mode to CQP, to avoid CreateConfig failed

---

media_driver/linux/common/codec/ddi/media_ddi_encode_avc.cpp
media_driver/linux/common/codec/ddi/media_ddi_encode_hevc.cpp
media_driver/linux/common/codec/ddi/media_ddi_encode_jpeg.cpp

remove the deprecated items of va from driver

---

media_driver/linux/common/codec/ddi/media_libva_encoder.cpp
media_driver/linux/common/ddi/media_libva.cpp
media_driver/linux/common/ddi/media_libva_caps.cpp

fix libva-utils conformance test issues

Conformance fix

---

media_driver/linux/common/ddi/media_libva.cpp

add I420 format for vaCreateImage

---

media_driver/linux/gen10/ddi/media_libva_caps_g10.cpp
media_driver/linux/gen8/ddi/media_libva_caps_g8.cpp
media_driver/linux/gen9/ddi/media_libva_caps_g9.cpp

Fixes: #153
Change-Id: I8a1e87b84e02224be3411949774e98ce38399a0a

Stop guessing bits locations while setting ROI caps

---

media_driver/linux/common/codec/ddi/media_ddi_decode_base.cpp
media_driver/linux/common/ddi/media_libva_caps.cpp
media_driver/linux/common/ddi/media_libva_caps.h

add check for vaCreateConfig parameters

---

README.md
distro_cmake.sh
media_driver/media_top_cmake.cmake
unified_cmake.sh

Change-Id: I60dd7083639597acc2b31c71a541b0c700cc6259

remove useless BUILD_ALONG_WITH_CMRTLIB

---

media_driver/linux/common/ddi/media_libva.cpp

add BGRX format support for vaCreateImage

---

media_driver/linux/common/ddi/media_libva.cpp

for the prime sharing, need to export surface handle to other components.

[DDI] enable vaExportSurfaceHandle

---

media_driver/linux/common/ddi/media_libva_caps.cpp

Signed-off-by: XinfengZhang <carl.zhang@intel.com> fix #159

add 10 bit caps report for HEVC main10 profile

---

media_driver/linux/common/codec/ddi/media_ddi_encode_mpeg2.cpp

following VAAPI definition. #fix issue #82

change the mb address value to the real MB address

---

README.md

Change-Id: Ie644b3bf80c657643b1a1a4601af83414dcde92b

update README for 18.2 release

---

distro_cmake.sh
unified_cmake.sh

1. Remove unified_cmake.sh file
2. add more flags in distro_cmake.sh

[Upstream] modify default building configuration

---

media_driver/agnostic/common/codec/hal/codechal_decode_vc1.cpp

Need to skip emulation prevetion byte when calculate the size and length
of packed slice data with emulation prevetion byte in packed slice header.

VC1 skip emulation prevention byte

---

media_driver/linux/common/codec/ddi/media_ddi_decode_jpeg.cpp
media_driver/linux/common/ddi/media_libva_common.cpp
media_driver/linux/common/ddi/media_libva_common.h

change surface format for jpeg 444 file decode

---

media_driver/linux/common/ddi/media_libva.cpp

[VP]Remove sw path and create vp context in DdiMedia_Putsurface

---

media_driver/agnostic/gen9/codec/hal/codechal_encode_hevc_g9.cpp
media_driver/agnostic/gen9_kbl/codec/hal/codechal_encode_hevc_g9_kbl.cpp

Signed-off-by: Qi, Stephanie <stephanie.qi@intel.com>

Enabled HEVC P frame encoder on KBL.

---

media_driver/linux/common/cm/cm_hal_os.cpp
media_driver/linux/common/cp/shared/cplib.cpp
media_driver/linux/common/ddi/media_libva.cpp
media_driver/linux/common/ddi/media_libva_common.h
media_driver/linux/common/ddi/media_libva_putsurface_linux.cpp
media_driver/linux/common/ddi/media_libva_util.cpp
media_driver/linux/common/os/mos_context_specific.cpp
media_driver/linux/common/os/mos_os_specific.c
media_driver/linux/common/os/mos_os_specific.h
media_driver/linux/ult/ult_app/cm/cm_test.h
media_driver/linux/ult/ult_app/ddi_test_caps.cpp
media_driver/linux/ult/ult_app/ddi_test_decode.cpp
media_driver/linux/ult/ult_app/ddi_test_encode.cpp
media_driver/linux/ult/ult_app/driver_loader.cpp
media_driver/linux/ult/ult_app/driver_loader.h
media_driver/linux/ult/ult_app/main.cpp
media_driver/linux/ult/ult_app/memory_leak_detector.cpp
media_driver/linux/ult/ult_app/memory_leak_detector.h
media_driver/media_top_cmake.cmake

switch to dynamic gmmlib

---

README.md

add decode/encode/VP feature support for ICL
add known limitaion for kernel requirement

Update readme for ICL open source

---

media_driver/agnostic/common/codec/hal/codechal_encode_jpeg.cpp
media_driver/agnostic/common/codec/hal/codechal_encode_jpeg.h
media_driver/agnostic/common/codec/shared/codec_def_encode.h
media_driver/linux/common/codec/ddi/media_ddi_encode_jpeg.cpp
media_driver/linux/common/codec/ddi/media_ddi_encode_jpeg.h
media_driver/linux/common/ddi/media_libva_caps.cpp

1. if the packed raw data just include jpeg application data segment
2. if the packed raw data include all of the application data
support these two packed data

change the capiblities and packed header raw data support

---

README.md

[upstream] update REAME

---

.travis.yml

1. remove gmm parameter in cmake command

simplify travis.yml build script

---

media_driver/linux/common/vp/ddi/media_libva_vp.c

Add output region of target surface

[VP]Fix issue #272.

---

media_driver/linux/common/ddi/media_libva_caps.cpp

Signed-off-by: Xiaoxia_Zhong <xiaoxia.zhong@intel.com>

Enable SkipFrame for AVC VDEnc.

---

media_driver/linux/common/ddi/media_libva.cpp
media_driver/linux/common/ddi/media_libva.h
media_driver/linux/common/ddi/media_libva_caps.cpp
media_driver/linux/common/ddi/media_libva_caps.h

Change-Id: Ic95d20042ea4c2262e066d685aa906a89cd96e4d

[VP] add RGBP format support in vaCreateImage

---

media_driver/CMakeLists.txt

1. don't override linker flag from user

fix github issue#313

---

README.md

Add format/max resolution for diff codec of decoding/encoding
Add format support list for VP features
Add docker image

Update readme for adding format/resolution support

---

media_driver/agnostic/gen10/codec/hal/codechal_encode_hevc_g10.cpp
media_driver/agnostic/gen10/codec/hal/codechal_vdenc_hevc_g10.cpp

[Encode] Fix clang compilation error #237

---

media_driver/linux/common/ddi/media_libva_putsurface_linux.cpp

[VP]Keep aspect ratio in PutSurface.

---

media_driver/linux/common/codec/ddi/media_ddi_encode_avc.cpp
media_driver/linux/common/codec/ddi/media_ddi_encode_base.cpp
media_driver/linux/common/ddi/media_libva_caps.cpp
media_driver/linux/common/ddi/media_libva_caps.h

Change-Id: I1a22aa036bf9438c491e8749087c8aa12217dbb0
Signed-off-by: xiaominc <xiaomin.chen@intel.com>

Enable QVBR for AVC DP encoding

---

media_driver/agnostic/common/os/mos_gpucontextmgr.cpp

Signed-off-by: Qi, Stephanie <stephanie.qi@intel.com>

Fix for VmRSS memory growth on VPP Close/Init.

---

media_driver/linux/common/ddi/media_libva_caps.cpp

Change-Id: Id56125ba59f12e98e4ceadb44fef9e2d3ed32a5e

[Encode] Enable QVBR for AVC VDENC encoding

---

media_driver/agnostic/common/codec/shared/codec_def_encode_avc.h
media_driver/agnostic/gen9_kbl/codec/hal/codechal_encode_avc_g9_kbl.cpp
media_driver/linux/common/codec/ddi/media_ddi_encode_avc.cpp
media_driver/linux/common/codec/ddi/media_ddi_encode_base.cpp
media_driver/linux/common/ddi/media_libva_caps.cpp
media_driver/linux/common/ddi/media_libva_caps.h

Change-Id: I2bd83d2d5dfd6b904283329b6acc07eab39bd91b

[Encode] Enable AVBR for AVC DP encoding on KBL

---

media_driver/agnostic/common/codec/hal/codechal_encode_avc.cpp

codechal_encode_avc: check return for Get**xDsSurface

---

README.md
docs/media_features.md

Add instroduction for ENABLE_KERNELS/FREE_KERNELS/BUILD_KERNELS.

Update readme with build options

---

media_driver/linux/common/os/i915/include/intel_chipset.h
media_driver/linux/gen9/ddi/media_sysinfo_g9.cpp

[Encode] Add some missing device IDs.

---

media_driver/linux/common/ddi/media_libva_caps.cpp
media_driver/linux/gen9/ddi/media_sku_wa_g9.cpp

Add VAProfileVP9Profile2 support for VA_RT_FORMAT_YUV420_10 for KBL

---

media_driver/linux/common/ddi/media_libva.cpp

Signed-off-by: Yu Kang Ku <yu.kang.ku@intel.com>

Allow I420 for surface creation

---

media_driver/linux/common/ddi/media_libva_util.cpp

Align the height for external surfaces

---

media_driver/linux/gen11/ddi/media_libva_caps_g11.cpp
media_driver/linux/gen11/ddi/media_libva_caps_g11.h

Add the decoding formats of VAProfileHEVCMain444 and VAProfileHEVCMain444_10.

---

media_driver/linux/common/codec/ddi/media_ddi_encode_vp8.cpp

maybe application does not register surfaces by vaCreateContext

register reconstruct surfaces for vp8 encode

---

media_driver/linux/common/ddi/media_libva_caps.cpp

Add I420 to supported Image formats

---

media_driver/agnostic/common/codec/hal/codechal_decode_mpeg2.cpp

Fixes #537
Signed-off-by: Dmitry Ermilov <dmitry.ermilov@intel.com>

[Decode] Added copy range check for BDW

---

media_driver/linux/common/ddi/media_libva.cpp

Signed-off-by: Furong Zhang(furong.zhang@intel.com)

Video Processing: Support XRGB in vaCreateImage.

---

media_driver/linux/common/ddi/media_libva.cpp
media_driver/linux/common/ddi/media_libva_caps.cpp

add Y210 format vaImage

---

media_driver/linux/common/ddi/media_libva.cpp
media_driver/linux/common/ddi/media_libva_caps.cpp

[VP]Add RGB565 support in vaCreateImage

---

media_driver/linux/common/ddi/media_libva.cpp
media_driver/linux/common/ddi/media_libva_caps.cpp

Add AYUV image format.

---

media_driver/linux/common/ddi/media_libva.cpp
media_driver/linux/common/ddi/media_libva_caps.cpp

Adding R8G8B8 24bit packed RGB support in vaCreateImage.

---

media_driver/linux/common/ddi/media_libva.cpp

add missing break in DdiMedia_CreateImage

---

media_driver/linux/common/ddi/media_libva.cpp
media_driver/linux/common/ddi/media_libva_common.h
media_driver/linux/common/ddi/media_libva_util.cpp
media_driver/linux/common/vp/ddi/media_libva_vp.c

And allocate tiling memory for VA_SURFACE_ATTRIB_MEM_TYPE_VA if required
from user application/library

ddi/media_libva: Distinguish VA memory type from external buffer flag

---

media_driver/linux/common/ddi/media_libva_caps.cpp

correct return value of QueryProcessingRate

---

media_driver/linux/common/ddi/media_libva.cpp
media_driver/linux/common/ddi/media_libva_common.h

remove duplicated va format to media format convertion function

---

media_driver/linux/common/codec/ddi/media_ddi_encode_vp8.cpp

reset BRC when the target bitrate or max bitrate changed

---

media_driver/agnostic/common/codec/hal/codechal_encoder_base.cpp

Signed-off-by: ZhiZhen Tang <zhizhen.tang@intel.com>

Fix transcoding performance issue on BDW.

---

media_driver/linux/common/vp/ddi/media_libva_vp.c

[VP]Add IMC3 in DdiVp_GetColorSpaceFromMediaFormat

---

README.md

Readme: update feature list for default and open source build

---

media_driver/linux/common/ddi/media_libva.cpp

Signed-off-by: Wangfei <fei.w.wang@intel.com>

add Y210/AYUV/Y410 format support in vaDeriveImage.

---

media_driver/agnostic/common/cm/cm_hal.cpp
media_driver/agnostic/common/codec/hal/codechal_decoder.cpp
media_driver/agnostic/common/codec/hal/codechal_encode_mpeg2.cpp
media_driver/agnostic/common/codec/hal/codechal_encode_vp8.cpp
media_driver/agnostic/common/codec/hal/codechal_vdenc_avc.cpp
media_driver/agnostic/common/codec/hal/codechal_vdenc_hevc.cpp
media_driver/agnostic/common/vp/hal/vphal_render_vebox_base.cpp
media_driver/agnostic/gen10/vp/hal/vphal_render_vebox_g10_base.cpp
media_driver/agnostic/gen11/codec/hal/codechal_vdenc_hevc_g11.cpp
media_driver/agnostic/gen11/vp/hal/vphal_render_vebox_g11_base.cpp
media_driver/agnostic/gen8/codec/hal/codechal_encode_avc_g8.cpp
media_driver/agnostic/gen8/hw/mhw_vebox_g8_X.cpp
media_driver/agnostic/gen8/vp/hal/vphal_render_vebox_g8_base.cpp
media_driver/agnostic/gen9/vp/hal/vphal_render_vebox_g9_base.cpp
media_driver/agnostic/gen9_bxt/codec/hal/codechal_encode_avc_g9_bxt.cpp
media_driver/agnostic/gen9_skl/codec/hal/codechal_encode_avc_g9_skl.cpp
media_driver/cmake/linux/media_compile_flags_linux.cmake
media_driver/linux/common/os/mos_os_specific.c

-Wparentheses will report some logical error, mainly for && and || priority, it's error-prone.  We do find and fix some issue in this commit. I will explain later.
Please only review last commit (3bae2ce). other commits will be merged by https://github.com/intel/media-driver/pull/240
Please carefully review this patch, do full round regression test for this patch

Do not ignore  -Wparentheses warning

---

media_driver/agnostic/gen11/codec/hal/codechal_decode_vc1_g11.cpp

Add addtionnal offset processing for VC1 advanced profile.

Fix VC1 decoding of advanced profile.

---

media_driver/linux/common/ddi/media_libva_caps.cpp

Add RT formats for VP9 profile 0~3.

---

media_driver/linux/common/ddi/media_libva_caps.cpp

- Added CQP mode to a list of supported HEVC FEI VA configs
- Treat FEI mode as ENCPAK if no VAConfigAttribFEIFunctionType provided
- Fixed query of supported attributes for HEVC FEI
Fixes #637
Signed-off-by: Dmitry Ermilov <dmitry.ermilov@intel.com>

Fixed HEVC FEI config creation

---

media_driver/linux/common/ddi/media_libva_util.cpp

UYVY format should use Y tiling.

---

media_driver/linux/common/ddi/media_libva_util.cpp

Make the width of created surface for P010, etc.

---

media_driver/linux/common/codec/ddi/media_ddi_encode_jpeg.cpp

Signed-off-by: Wangfei <fei.w.wang@intel.com>

[Encode] Add UYVY to jpeg encode convert media format to surface format.

---

media_driver/agnostic/gen11/codec/hal/codechal_encode_jpeg_g11.cpp

Based on comparing with Gen9 platform, need difference command
generating for app data or not on Gen11 platform.

Fix JPEG encoding based on app data or not.

---

media_driver/linux/common/ddi/media_libva.cpp

Add A2RGB10 and A2BGR10 for the function of vaCreateImage.

---

media_driver/linux/common/codec/ddi/media_ddi_encode_mpeg2.cpp

set mpeg2 encode default fps to 30

---

media_driver/linux/common/ddi/media_libva.cpp

[VP] Add tile type for image creation

---

README.md
docs/media_features.md

Highlight two build mode, full features build and open source build, and
introduce related build options.

Update README to clarify different build mode

---

media_driver/linux/common/ddi/media_libva_caps.cpp

set vp8 encode max resolution to 4k

---

media_driver/linux/common/ddi/media_libva.cpp

should not use this value, it will changed by different libva version

removed va enum max type VABufferTypeMax from media driver

---

media_driver/linux/common/ddi/media_libva.cpp

Fix 10bit RGB support in vaExportSurfaceHandle.

---

media_driver/linux/common/ddi/media_libva.h
media_driver/linux/common/ddi/media_libva_caps.cpp
media_driver/linux/common/ddi/media_libva_caps.h

Add A2RGB10 and A2BGR10 in vaQuerySurfaceAttributes.

---

media_driver/linux/common/ddi/media_libva_util.cpp

check pitch from application for user ptr

---

media_driver/linux/common/ddi/media_libva.cpp

fix potential threading issue, avoid reusing existing vpp context

---

media_driver/agnostic/gen11_icllp/media_interfaces/media_interfaces_g11_ehl.cpp

When -DENABLE_KERNELS=OFF, add some macros to fix build issue.

[Encode] Fix build issue about EHL

---

media_driver/linux/common/ddi/media_libva.cpp

Align the tile type of image for UYVY/YVYU/VYUY with surface tile type
fix #757

[VP] Change image tile type for UYVY

---

media_driver/linux/gen9/ddi/media_sku_wa_g9.cpp

Signed-off-by: Furong Zhang <furong.zhang@intel.com>

Enable HDR Tone Mapping on GLK.

---

media_driver/linux/gen12/ddi/media_libva_caps_g12.cpp

this will fix https://gitlab.freedesktop.org/gstreamer/gstreamer-vaapi/issues/223

Gen12: hevc, fix caps query for 10 bits decoder

---

media_driver/linux/common/ddi/media_libva.cpp

Add fix patch which left by previous patch

[VP] Add XRGB/XBGR 10bit.

---

media_driver/linux/common/ddi/media_libva_caps.cpp

fix the caps report , low delay B support is for HEVC

---

media_driver/linux/common/codec/ddi/media_ddi_encode_avc.cpp

Signed-off-by: Zhizhen Tang <zhizhen.tang@intel.com>

Fix coding style problem

---

CMakeLists.txt

Master code target 20.2, so let us reflect this in sources.

Version bump

---

media_driver/linux/common/ddi/media_libva.cpp
media_driver/linux/common/vp/ddi/media_libva_vp.c

Fix performance drop issue (intel#903), allocate temp surface as linear and use VP to do swizzle, copy surface to image by one memcpy.

[Media Common]Fix performance drop issue

---

media_driver/linux/common/vp/ddi/media_libva_vp.c

…Format
This fixes the pipeline below
GST_GL_PLATFORM=glx gst-launch-1.0 filesrc location=input.444.h265 !
h265parse ! vaapih265dec ! vaapipostproc ! glimagesink

vp: Add AYUV/Y210/Y410/P016/Y216/Y416 in DdiVp_GetColorSpaceFromMediaFormat

---

media_driver/linux/gen12/ddi/media_libva_caps_g12.cpp

including vp9 10bit and hevc screen-extended-main-444
Fixes #893
Fixes #841
Signed-off-by: tim.xie <tim.xie@intel.com>

fix decode caps related issue

---

media_driver/linux/gen12/ddi/media_libva_caps_g12.cpp

add HEVC VME MaxSlice caps

---

media_driver/agnostic/gen12/codec/hal/codechal_decode_scalability_g12.cpp

Fixes:#965
Initialize the variable to fix 16.04 build issue
Change-Id: Ifaba0cde056b90c4a7fc259e8620b162cf42ca62

[Decode] Fix ubuntu 16.04 build issue

---

media_driver/linux/common/ddi/media_libva_caps.cpp

Bug fix for capability of  MPEG2. fixed #483

Correct MAX resolution capability of MPEG2

---

media_driver/linux/common/ddi/media_libva.cpp

implementation vaSyncBuffer in driver side with timeout

vaSyncBuffer driver implementation

---

media_driver/linux/common/codec/ddi/media_ddi_decode_avc.cpp

Avoid search invalid ref frames/fields.

---

media_driver/linux/common/vp/ddi/media_libva_vp.c

update ChromaSiting default value for linux ProCamp.
issue link: https://github.com/intel/media-driver/issues/686
Signed-off-by: Alex1 Zhang <alex1.zhang@intel.com>

[VP] update ChromaSiting default value for Linux ProCamp

---

media_driver/linux/common/ddi/media_libva.h
media_driver/linux/common/ddi/media_libva_caps.cpp
media_driver/linux/common/ddi/media_libva_caps.h

Signed-off-by: Fei Wang <fei.w.wang@intel.com>

[VP] Add X2RGB10 and X2BGR10 in vaQuerySurfaceAttributes

---

media_driver/linux/common/ddi/media_libva.cpp

Add 3-plane surface support in vaExportSurfaceHandle for non-MMC.

---

media_driver/linux/common/ddi/media_libva.cpp

reproduce steps:
1. run gst-launch-1.0 -v tee name = t filesrc location = ~/cin.264 ! h264parse ! vaapih264dec ! t.  t. ! queue max-size-buffers=5 ! vaapipostproc ! "video/x-raw(memory:VASurface), format=NV12, width=320, height=240" ! vaapih264enc  ! fakesink
2. you will see "[LIBVA]:CRITICAL - DdiMedia_HeapDestroy:1382: APP does not destroy all the VPs"
gstvaapi will use vaGetImage to test driver capablities, it may give driver wrong input/output format
we need make sure no resource leak at anytime.

DdiMedia_GetImage: fix vp context leak for error return

---

media_driver/agnostic/gen10/renderhal/renderhal_g10.cpp
media_driver/agnostic/gen11/renderhal/renderhal_g11.cpp
media_driver/agnostic/gen12/renderhal/renderhal_g12.cpp
media_driver/agnostic/gen9/renderhal/renderhal_g9.cpp

Fix compilation error in Debug build with clang-11 enabled.

Compilation errors with clang

---

Tools/MediaDriverTools/Android/mk/media_driver.tpl
media_driver/linux/common/os/i915/include/mos_bufmgr.h
media_driver/linux/common/os/i915/mos_bufmgr_api.c
media_driver/linux/ult/libdrm_mock/CMakeLists.txt
media_driver/linux/ult/libdrm_mock/mos_bufmgr_api_mock.c
media_driver/media_top_cmake.cmake

Signed-off-by: Carl Zhang <carl.zhang@intel.com>

remove unnecessary dependency - libpciaccess

---

README.md

clarify the huc enabling in readme

---

media_driver/linux/common/ddi/media_libva_caps.cpp
media_driver/linux/gen11/ddi/media_libva_caps_g11.cpp
media_driver/linux/gen12/ddi/media_libva_caps_g12.cpp

correct the reference capibility for gen11 and gen12

---

media_driver/linux/gen12/ddi/media_libva_caps_g12.cpp

correct HEVC frame type capability of TGL HEVC support I B lowdelay B

---

cmrtlib/linux/CMakeLists.txt
media_driver/cmake/linux/media_include_paths_linux.cmake
media_driver/linux/ult/CMakeLists.txt

unify libva dependencies to 2.8.0

---

media_driver/linux/gen12/codec/ddi/media_ddi_decode_av1_g12.cpp
media_driver/linux/gen12/codec/ddi/media_ddi_decode_av1_g12.h

Fix AV1 film grain output surface initialization

---

media_driver/linux/common/ddi/media_libva_caps.cpp
media_driver/linux/gen12/ddi/media_libva_caps_g12.cpp

correct attribute of HEVC SCC encode surfaces

---

media_driver/media_driver_next/agnostic/common/codec/hal/dec/av1/features/decode_av1_basic_feature.cpp

Update surface info of m_destSurface when film grain is enabled

---

cmrtlib/linux/share/cm_def_os.h
cmrtlib/linux/share/cm_rt_def_os.h
media_driver/linux/common/codec/ddi/media_ddi_decode_vp9.cpp
media_driver/linux/common/ddi/media_libva.cpp
media_driver/linux/common/ddi/media_libva_caps.cpp
media_driver/linux/common/ddi/media_libva_common.cpp
media_driver/linux/common/ddi/media_libva_common.h
media_driver/linux/common/ddi/media_libva_util.cpp
media_driver/linux/common/os/mos_interface.cpp
media_driver/linux/common/vp/ddi/media_libva_vp.c
media_driver/linux/gen11/ddi/media_libva_caps_g11.cpp
media_driver/linux/gen12/codec/ddi/media_ddi_decode_hevc_g12.cpp
media_driver/linux/gen12/ddi/media_libva_caps_g12.cpp

Add Y212 and Y412 format

---

media_driver/linux/gen12/ddi/media_libva_caps_g12.cpp

Signed-off-by: Hirokazu Honda <hiroh@chromium.org>

Handle VAConfigAttribRTFormat query to AV1 profiles case explicitly

---

media_driver/agnostic/common/cm/cm_device_rt_base.cpp
media_driver/agnostic/common/cm/cm_device_rt_base.h
media_driver/agnostic/common/os/mos_interface.h
media_driver/agnostic/common/os/mos_os.h
media_driver/linux/common/codec/ddi/media_ddi_encode_base.cpp
media_driver/linux/common/codec/ddi/media_libva_decoder.cpp
media_driver/linux/common/codec/ddi/media_libva_decoder.h
media_driver/linux/common/codec/ddi/media_libva_encoder.cpp
media_driver/linux/common/codec/ddi/media_libva_encoder.h
media_driver/linux/common/ddi/media_libva_caps.cpp
media_driver/linux/common/ddi/media_libva_caps.h
media_driver/linux/common/ddi/media_libva_common.cpp
media_driver/linux/common/ddi/media_libva_common.h
media_driver/linux/common/os/i915_production/mos_bufmgr.c
media_driver/linux/common/os/mos_context_specific.cpp
media_driver/linux/common/os/mos_context_specific.h
media_driver/linux/common/os/mos_interface.cpp
media_driver/linux/common/os/mos_os_specific.c
media_driver/linux/common/vp/ddi/media_libva_vp.c
media_driver/linux/common/vp/ddi/media_libva_vp.h
media_driver/media_driver_next/linux/common/os/mos_gpucontext_specific_next.cpp
media_driver/media_driver_next/linux/common/os/mos_gpucontext_specific_next.h

[Media]Implemented dynamic Gpu session priority
Implemented the media and vp Gpu context priority setting.
Signed-off-by: Wang Dylan <dylan.wang@intel.com>

[Media]Implemented dynamic Gpu session priority

---

media_driver/agnostic/gen11/hw/vdbox/mhw_vdbox_hcp_g11_X.cpp
media_driver/agnostic/gen12/hw/vdbox/mhw_vdbox_hcp_g12_X.cpp

Use different default alpha value for 12 bit decoding

---

media_driver/linux/ult/libdrm_mock/mos_bufmgr_mock.c

Fix ult build issue.

---

media_driver/linux/common/ddi/media_libva_util.cpp

Fix odd resolution handling of I420/YV12 formats

---

media_driver/agnostic/gen9_glk/codec/hal/codechal_encode_hevc_g9_glk.cpp

Together with  #1005 can fix following 2 issues. Fixed #930, Fixed #733.

Fix HEVC encoding failed on P frame issue on GLK

---

.github/workflows/ubuntu.yml

Example of execution: https://github.com/dvrogozh/media-driver/actions/runs/431312959. We need to merge this PR in to make it run in the intel/media-driver repo.

ci: enable github actions

---

media_driver/linux/common/ddi/media_libva_util.cpp

Need to upgrade gmmlib version to 6f15b795e1511febf233b42d7dde603f52fcfdab

Fix external surface issue using new gmm API.

---

media_driver/linux/common/ddi/media_libva_util.cpp

fix memory leak caused by external surface descriptor

---

cmrtlib/linux/CMakeLists.txt

[cmrtlib] remove sse flags

---

media_driver/agnostic/common/vp/hal/vphal_common.h

Issue report in:
https://gitlab.freedesktop.org/gstreamer/gstreamer-vaapi/-/issues/303
Platform: TGL-U
Signed-off-by: Lim Siew Hoon <siew.hoon.lim@intel.com>

changed VPHAL_MAX_SOURCES set to 65

---

media_driver/agnostic/gen9_glk/codec/hal/codechal_encode_hevc_g9_glk.cpp

Make HEVC ME kernel to support P frame on GLK

Fix encode issue for HEVC on GLK

---

cmrtlib/linux/share/cm_def_os.h
cmrtlib/linux/share/cm_rt_def_os.h
media_driver/linux/common/ddi/media_libva.cpp
media_driver/linux/common/ddi/media_libva_caps.cpp
media_driver/linux/common/ddi/media_libva_common.cpp
media_driver/linux/common/ddi/media_libva_common.h
media_driver/linux/common/ddi/media_libva_util.cpp
media_driver/linux/common/os/mos_interface.cpp
media_driver/linux/common/vp/ddi/media_libva_vp.c
media_driver/linux/gen11/ddi/media_libva_caps_g11.cpp
media_driver/linux/gen12/ddi/media_libva_caps_g12.cpp

Support 0YUV format from decode side:
XYUV(8bit)

[Decode] Add 0YUV format for decode

---

media_driver/agnostic/common/vp/hal/vphal_render_fast1ton.cpp
media_driver/agnostic/common/vp/hal/vphal_render_fast1ton.h

Fixes: #1216
Signed off by: jay.yang@intel.com

Update vphal_render_fast1ton file liscense

---

CMakeLists.txt

add project to the top-level cmake

---

media_driver/agnostic/common/codec/hal/codechal_encode_sfc_base.cpp

initialize the array before use it

---

media_driver/linux/common/codec/ddi/media_ddi_encode_vp8.cpp
media_driver/linux/common/codec/ddi/media_ddi_encode_vp8.h

reset brc when frame rate changes for VP8e

---

media_driver/linux/common/codec/ddi/media_libva_decoder.cpp

[Decode] access volation when get status report

---

media_driver/agnostic/gen12/codec/hal/codechal_decode_scalability_g12.cpp
media_driver/linux/common/os/i915/include/uapi/README
media_driver/linux/common/os/i915/include/uapi/drm_mode.h
media_driver/linux/common/os/i915/include/uapi/i915_drm.h
media_driver/linux/common/os/i915/mos_bufmgr.c
media_driver/linux/gen12/ddi/media_sku_wa_g12.cpp

This PR depend on this change https://patchwork.freedesktop.org/series/92789/

Support parallel submission for ADLP

---

.github/ISSUE_TEMPLATE/0-bug-issue.md

PR to "patch to fix the issue"

change the issue template to avoid confusion of PR

---

.github/workflows/ubuntu.yml
media_driver/agnostic/common/cm/cm_mem_sse2_impl.cpp

Fixes: https://github.com/intel/media-driver/issues/1344

build: fix build with gcc-11

---

media_driver/linux/gen9/ddi/media_sku_wa_g9.cpp
media_driver/linux/ult/ult_app/RefCapsTable_BXT.h
media_driver/media_interface/media_interfaces_m9_bxt/media_interfaces_g9_bxt.cpp
media_driver/media_interface/media_interfaces_m9_bxt/media_interfaces_g9_bxt.h

enable VP8 encode for BXT and APL

---

media_common/agnostic/common/os/mos_utilities.h
media_driver/agnostic/common/codec/hal/codechal_encoder_base.cpp
media_driver/linux/common/codec/ddi/media_ddi_decode_vp8.cpp
media_softlet/agnostic/common/os/mos_utilities_next.h

Fixes #1354. It is to fix the compiling issue for gcc12.0.1.
[-Werror=address] [-Werror=dangling-pointer=][-Werror=alloc-size-larger-than=]
Signed-off-by: Wang, Pingli <pingli.wang@intel.com>

Fixes #1354

---

docs/media_features.md

1. Correct supporting formats for Gen12
2. Add note for max resolution for DG2/ATSM

Update media feature table

---

media_driver/agnostic/common/codec/hal/codechal_decoder.cpp

[Decode] Correct the status report reigster for vp9

---

media_driver/linux/common/ddi/media_libva.cpp

Modify Query VP Filters

---

media_driver/linux/Xe_M/ddi/media_libva_caps_dg2.cpp
media_driver/linux/gen12/ddi/media_libva_caps_g12.cpp

1. optimize call flow
2. add a new attribute list for SCC to correct some incorrect values
3. fixes #1391

Optimize SCC capability report for Gen12 HEVC

---

media_driver/agnostic/common/codec/hal/codechal_decoder.cpp

[Decode] Add more strict check for decode error

---

media_driver/linux/Xe_M/ddi/media_libva_caps_dg2.cpp

Signed-off-by: Fei Wang <fei.w.wang@intel.com>

[Encode] fix AV1 caps for obu size bytes support

---

media_driver/agnostic/common/codec/hal/codechal_decoder.cpp
media_driver/agnostic/common/codec/hal/codechal_encode_avc.cpp
media_driver/agnostic/gen12/codec/hal/codechal_decode_hevc_g12.cpp
media_driver/media_softlet/agnostic/Xe_M/Xe_M_base/codec/hal/dec/hevc/packet/decode_hevc_packet_real_tile_m12.cpp
media_driver/media_softlet/agnostic/gen12/codec/hal/dec/av1/packet/decode_av1_packet_g12.cpp
media_softlet/agnostic/common/shared/media_debug_interface.cpp

[Decode] Add the null check to avoid crash

---

media_driver/agnostic/common/vp/hal/vphal_render_16alignment.cpp
media_driver/agnostic/common/vp/hal/vphal_render_16alignment.h

[License]Add explicit grant of license

---

media_driver/linux/Xe_M/ddi/media_libva_caps_dg2.cpp
media_driver/linux/Xe_M/ddi/media_libva_caps_pvc.cpp
media_driver/linux/common/ddi/media_libva.h
media_driver/linux/common/ddi/media_libva_caps.cpp
media_driver/linux/gen12/ddi/media_libva_caps_g12.cpp

report PCI ID though VADisplayPCIID

---

.github/workflows/ubuntu.yml

Change-Id: I67d2744402a98f605cfa45e3018712da5e103cd8

ci: switch to ubuntu 22.04 from ubuntu 21.10 for gcc-11

---

media_driver/agnostic/common/codec/hal/codechal_vdenc_hevc.cpp
media_driver/agnostic/gen12/codec/hal/codechal_vdenc_avc_g12.cpp

If the base address of the staging buffer is not 64 bytes aligned,
it can bring in performance issue when memcpy between staging buffer
and the graphics buffer.
Signed-off-by: Zhizhen Tang <zhizhen.tang@intel.com>

[Encode] Fix MB QP Data shadow buffer has potential alignment issue

---

media_driver/linux/common/os/mos_os_specific.c
media_softlet/linux/common/os/private/mos_os_specific.cpp

Fix sleep issue

---

media_driver/agnostic/Xe_M/Xe_XPM/hw/vdbox/mhw_vdbox_mfx_xe_xpm.cpp
media_driver/agnostic/gen12/hw/vdbox/mhw_vdbox_mfx_g12_X.cpp
media_softlet/agnostic/common/codec/hal/dec/mpeg2/features/decode_mpeg2_reference_frames.cpp

[Decode] Add null point check for reference

---

media_driver/linux/common/codec/ddi/media_ddi_encode_av1.cpp

AV1 Linux: Remove Hierarchy flag wa
Signed-off-by: RachelChengRJ <rachel.cheng@intel.com>

[Encode] Remove Hierarchy flag wa

---

media_softlet/agnostic/common/os/mos_utilities.h
media_softlet/linux/common/os/osservice/mos_utilities_specific.cpp

Fix the 32 bit build regression

---

.github/workflows/ubuntu.yml

update github actions dependencies for libva

---

media_driver/agnostic/Xe_M/Xe_HPM/codec/media_srcs.cmake
media_driver/agnostic/Xe_M/Xe_XPM/vp/media_srcs.cmake
media_driver/agnostic/Xe_M/Xe_XPM_plus/codec/media_srcs.cmake
media_driver/agnostic/Xe_M/Xe_XPM_plus/vp/media_srcs.cmake

Fix build failure with full free kernel

---

media_softlet/agnostic/common/vp/hal/packet/vp_render_hdr_kernel.cpp
media_softlet/agnostic/common/vp/hal/packet/vp_render_hdr_kernel.h

Fixed #1519
Signed-off-by: Gu, Lihao lihao.gu@intel.com

Fix hdr render issue

---

media_driver/linux/common/codec/ddi/media_libva_decoder.cpp

[Decode] Correct decode buffer heap nums

---

media_driver/media_top_cmake.cmake
media_softlet/linux/common/os/osservice/media_srcs.cmake
media_softlet/linux/common/os/osservice/mos_compat.h.in
media_softlet/linux/common/os/osservice/mos_utilities_specific.cpp

Fixes: #1533
Change-Id: I81bcdb5e65c26f94b174af9b5e6218c14601c50f

build: check for backtrace(3) via FindBacktrace

---

media_driver/agnostic/common/cm/cm_ish_base.cpp

Fix potential crash with uninitialized pointer

---

media_driver/linux/common/ddi/media_libva_util.cpp
media_softlet/linux/common/ddi/media_libva_util_next.cpp

Fix print message format '%lu' issue

---

media_softlet/linux/common/codec/enc/ddi/ddi_encode_functions.cpp
media_softlet/linux/common/ddi/media_libva_interface_next.cpp

1. Removed null_check of attribList in QuerySurfaceAttributes
2. Removed null_check of attribList in CreateConfig
cc: carl.zhang@intel.com

[Media Common] Fix invalid parameter error

---

media_driver/agnostic/gen12/codec/hal/codechal_decode_hevc_long_g12.cpp

Signed-off-by: Zhizhen Tang <zhizhen.tang@intel.com>

[Decode] Added error protection of corrupt stream

---

media_softlet/linux/common/codec/dec/ddi/ddi_decode_functions.cpp
media_softlet/linux/common/ddi/ddi_media_functions.cpp
media_softlet/linux/common/ddi/media_capstable_specific.cpp
media_softlet/linux/common/ddi/media_libva_caps_next.cpp
media_softlet/linux/common/ddi/media_libva_interface_next.cpp
media_softlet/linux/xe_lpm_plus_r0/decode/av1/ddi/capstable_data_av1_decode_xe_lpm_plus_r0_specific.h
media_softlet/linux/xe_lpm_plus_r0/decode/avc/ddi/capstable_data_avc_decode_xe_lpm_plus_r0_specific.h
media_softlet/linux/xe_lpm_plus_r0/decode/hevc/ddi/capstable_data_hevc_decode_xe_lpm_plus_r0_specific.h
media_softlet/linux/xe_lpm_plus_r0/decode/jpeg/ddi/capstable_data_jpeg_decode_xe_lpm_plus_r0_specific.h
media_softlet/linux/xe_lpm_plus_r0/decode/mpeg2/ddi/capstable_data_mpeg2_decode_xe_lpm_plus_r0_specific.h
media_softlet/linux/xe_lpm_plus_r0/decode/vp8/ddi/capstable_data_vp8_decode_xe_lpm_plus_r0_specific.h
media_softlet/linux/xe_lpm_plus_r0/decode/vp9/ddi/capstable_data_vp9_decode_xe_lpm_plus_r0_specific.h

Fix error when createConfig() with null attrib_list.

[Decode] Improve negative case check

---

media_driver/agnostic/gen11/codec/hal/codechal_vdenc_hevc_g11.cpp
media_driver/agnostic/gen11/codec/hal/codechal_vdenc_hevc_g11.h
media_driver/agnostic/gen11/codec/hal/codechal_vdenc_vp9_g11.cpp

This commit fix the compilation error when setting -DGEN10=OFF
Fix for https://github.com/intel/media-driver/issues/1065

[Encode] Fix build issue when setting -DGEN10=OFF

---

media_driver/linux/common/ddi/media_libva.cpp

[Decode] Close the hanle if return error to avoid file handles leak

---

media_softlet/linux/Xe_M_plus/ddi/media_libva_caps_mtl_base.cpp
media_softlet/linux/common/ddi/media_libva_util_next.cpp

description: use possible upstream definition of CCS modifier
Signed-off-by: Jianxing Cai [jianxing.cai@intel.com](mailto:jianxing.cai@intel.com)

use possible upstream definition of CCS modifier

---

media_driver/media_softlet/agnostic/Xe_M/Xe_M_base/codec/hal/dec/vp9/features/media_srcs.cmake
media_driver/media_softlet/agnostic/Xe_M/Xe_M_base/codec/hal/dec/vp9/mmc/media_srcs.cmake
media_driver/media_softlet/agnostic/Xe_M/Xe_M_base/codec/hal/dec/vp9/packet/media_srcs.cmake
media_driver/media_softlet/agnostic/Xe_M/Xe_M_base/codec/hal/dec/vp9/pipeline/media_srcs.cmake

[Decode] Fix compiling issue for vp9

---

media_driver/agnostic/gen12/codec/hal/codechal_vdenc_vp9_g12.cpp

If the padding row is N, repeatly copy the last row into the N padding rows, instead of copy whole last N rows into padding.

[VP9][Encode] Fix unaligned height static content encoding quality

---

media_softlet/agnostic/common/codec/hal/enc/hevc/features/encode_hevc_basic_feature.cpp
media_softlet/agnostic/common/codec/hal/enc/hevc/features/encode_hevc_basic_feature.h

HEVC encoder: handle VAQMatrixBufferHEVC according to VAAPI on xe

---

docs/media_features.md

Correct supported vp9 output format and update more info for 12bit decoding

[Decode] update feature list

---

media_softlet/linux/common/os/i915/mos_bufmgr.c

Add code for old kernel compatibility

---

media_driver/agnostic/Xe_M/Xe_XPM/hw/mhw_vebox_xe_xpm.h
media_driver/agnostic/gen12/codec/hal/codechal_encode_csc_ds_mdf_g12.h
media_driver/agnostic/gen12/hw/mhw_vebox_g12_X.h
media_driver/agnostic/gen12/hw/vdbox/mhw_vdbox_avp_generic.h
media_driver/agnostic/gen9/codec/hal/codechal_encode_avc_g9.h
media_driver/agnostic/gen9_skl/codec/hal/codechal_fei_hevc_g9_skl.cpp
media_driver/media_softlet/agnostic/Xe_M/Xe_HPM/shared/mediacopy/media_copy_xe_hpm.h
media_driver/media_softlet/agnostic/Xe_M/Xe_XPM_base/shared/mediacopy/media_copy_xe_xpm_base.h
media_driver/media_softlet/agnostic/Xe_M/Xe_XPM_plus/shared/mediacopy/media_copy_xe_xpm_plus.h
media_driver/media_softlet/agnostic/gen12_base/codec/hal/dec/shared/hucitf/decode_huc_packet_creator_g12.h
media_driver/media_softlet/agnostic/m12/m12_0/shared/mediacopy/media_copy_m12_0.h
media_softlet/agnostic/Xe_M_plus/Xe_LPM_plus_base/shared/mediacopy/media_copy_xe_lpm_plus_base.h
media_softlet/agnostic/common/codec/hal/enc/shared/bufferMgr/encode_tracked_buffer_queue.cpp
media_softlet/agnostic/common/codec/hal/enc/shared/bufferMgr/encode_tracked_buffer_queue.h
media_softlet/agnostic/common/shared/media_debug_serializer.h
media_softlet/agnostic/common/shared/scalability/media_scalability_multipipe.cpp
media_softlet/agnostic/common/shared/scalability/media_scalability_multipipe.h

Fix GCC13 build errors

---

media_driver/linux/common/ddi/media_libva_caps.cpp
media_softlet/linux/common/ddi/media_libva_util_next.cpp

[Media Common] Return correct modifier for I915_TILING_Y

---

media_softlet/linux/common/os/osservice/mos_utilities_specific.cpp

Fixes: https://github.com/intel/media-driver/issues/1654

[Media Common] [VP] Guard Regkey file auto create in release vesion

---

media_softlet/agnostic/common/codec/hal/dec/hevc/features/decode_hevc_basic_feature.cpp
media_softlet/agnostic/common/codec/hal/dec/hevc/features/decode_hevc_reference_frames.cpp

Reverts intel/media-driver#1744

Revert "[Decode] Optimize error syntax check for hevc"

---

media_driver/agnostic/common/codec/hal/codechal_decode_hevc.cpp

Otherwise it might result in GPU hang on some HWs

codechal_decode_hevc: avoid decoding a non-intra frame without refs

---

media_driver/cmake/linux/media_feature_flags_linux.cmake

Enable Xe KMD by default

---

media_driver/cmake/linux/media_compile_flags_linux.cmake
media_softlet/cmake/linux/media_compile_flags_linux.cmake

[Media Common] [VP] Disable overloaded virtual being hidden warning

---

cmrtlib/linux/hardware/cm_device_os.cpp
media_driver/linux/common/ddi/media_libva.h
media_softlet/agnostic/common/vp/hal/bufferMgr/vp_allocator.cpp
media_softlet/agnostic/common/vp/kdll/hal_kerneldll_next.c
media_softlet/linux/common/os/osservice/mos_utilities_specific.cpp
media_softlet/linux/common/os/xe/mos_bufmgr_xe.c

Change-Id: I031365909dbaec29e4c998891e28c16e7f38e530

Fixed compilation issues in Android

---

media_common/linux/common/os/mos_defs_specific.h

Fix missing cstdint for GCC 15
